# ==============================================================================
# Public Human TB Granuloma - Cluster-wise Spatial Highlighting
# ==============================================================================
#
# Purpose:
#   Generate cluster-wise spatial highlighting plots for public human lung
#   Mycobacterium tuberculosis granuloma spatial transcriptomics data.
#
# Required input:
#   human_tb:
#     A processed Seurat spatial object generated by:
#       10_Public_Human_TB_Lung_Granuloma_ST_Analysis.R
#
# Main outputs generated in memory:
#   cluster_highlight_plots
#
# Notes:
#   This script does not save figures to disk.
#   Users can export plots as needed.
# ==============================================================================


# ==============================================================================
# --- 0. Load R packages ---
# ==============================================================================

suppressMessages({
  library(Seurat)
  library(ggplot2)
  library(RColorBrewer)
  library(stringr)
  library(scales)
})

options(future.globals.maxSize = 9e10)
options(Seurat.object.assay.version = "v5")


# ==============================================================================
# --- 1. Example input object loading ---
# ==============================================================================

project_dir <- "path/to/project"

human_tb_object_path <- file.path(
  project_dir,
  "processed_objects",
  "public_human_TB_granuloma_processed.rds"
)

if (!exists("human_tb")) {
  human_tb <- readRDS(human_tb_object_path)
}

message("Input object:")
print(human_tb)


# ==============================================================================
# --- 2. Set cluster identities ---
# ==============================================================================

# Default clustering metadata column.
# Modify this value if another metadata column stores the clustering result.
cluster_metadata_column <- "seurat_clusters"

if (!cluster_metadata_column %in% colnames(human_tb@meta.data)) {
  stop(
    "Cluster metadata column not found: ",
    cluster_metadata_column
  )
}

current_clusters_char <- as.character(
  human_tb@meta.data[[cluster_metadata_column]]
)

sorted_cluster_levels <- stringr::str_sort(
  unique(current_clusters_char),
  numeric = TRUE
)

human_tb@meta.data[[cluster_metadata_column]] <- factor(
  current_clusters_char,
  levels = sorted_cluster_levels
)

Idents(human_tb) <- human_tb@meta.data[[cluster_metadata_column]]

active_ident_levels <- levels(Idents(human_tb))
num_actual_clusters <- length(active_ident_levels)

message("Clusters to highlight:")
print(active_ident_levels)


# ==============================================================================
# --- 3. Define cluster color mapping ---
# ==============================================================================

base_colors_paired <- brewer.pal(
  min(12, brewer.pal.info["Paired", "maxcolors"]),
  "Paired"
)

base_colors_dark2 <- brewer.pal(
  min(8, brewer.pal.info["Dark2", "maxcolors"]),
  "Dark2"
)

base_colors_set3 <- brewer.pal(
  min(12, brewer.pal.info["Set3", "maxcolors"]),
  "Set3"
)

base_colors_set1 <- brewer.pal(
  min(9, brewer.pal.info["Set1", "maxcolors"]),
  "Set1"
)

all_available_colors <- c(
  base_colors_paired,
  base_colors_dark2,
  base_colors_set3,
  base_colors_set1,
  colors()[grep("blue|green|orange|purple|yellow|pink|brown", colors())]
)

if (length(all_available_colors) < num_actual_clusters) {
  warning(
    "Available colors are fewer than actual clusters. ",
    "Colors will be recycled."
  )
  specific_cluster_colors_values <- rep(
    all_available_colors,
    length.out = num_actual_clusters
  )
} else {
  specific_cluster_colors_values <- all_available_colors[
    seq_len(num_actual_clusters)
  ]
}

specific_cluster_colors_map <- setNames(
  specific_cluster_colors_values,
  active_ident_levels
)


# ==============================================================================
# --- 4. Helper function for cluster-wise spatial highlighting ---
# ==============================================================================

make_cluster_highlight_plot <- function(
    object,
    cluster_id,
    cluster_metadata_column = "seurat_clusters",
    cluster_color_map,
    temp_highlight_col_name = "temp_plotting_group_target_only",
    point_size_factor = 2,
    image_alpha = 0.8,
    crop = FALSE,
    stroke = 0
) {
  
  target_color_for_highlight <- cluster_color_map[[cluster_id]]
  
  if (is.na(target_color_for_highlight) || is.null(target_color_for_highlight)) {
    target_color_for_highlight <- "red"
  }
  
  object@meta.data[[temp_highlight_col_name]] <- ifelse(
    as.character(object@meta.data[[cluster_metadata_column]]) == cluster_id,
    "HighlightedCluster",
    "OtherClusters"
  )
  
  object@meta.data[[temp_highlight_col_name]] <- factor(
    object@meta.data[[temp_highlight_col_name]],
    levels = c("HighlightedCluster", "OtherClusters")
  )
  
  manual_colors_for_plot <- c(
    "HighlightedCluster" = target_color_for_highlight,
    "OtherClusters" = NA_character_
  )
  
  p <- SpatialDimPlot(
    object = object,
    group.by = temp_highlight_col_name,
    pt.size.factor = point_size_factor,
    crop = crop,
    stroke = stroke,
    image.alpha = image_alpha,
    label = FALSE
  ) +
    scale_fill_manual(
      values = manual_colors_for_plot,
      na.value = "transparent"
    ) +
    ggtitle(
      paste("Human TB: spatial distribution of cluster", cluster_id)
    ) +
    theme(
      legend.position = "none",
      plot.title = element_text(
        hjust = 0.5,
        face = "bold",
        size = 16
      )
    )
  
  return(p)
}


# ==============================================================================
# --- 5. Generate cluster-wise spatial highlighting plots ---
# ==============================================================================

cluster_highlight_plots <- list()

for (current_cluster_id in active_ident_levels) {
  
  message("Generating spatial highlight plot for cluster: ", current_cluster_id)
  
  p_individual <- tryCatch(
    {
      make_cluster_highlight_plot(
        object = human_tb,
        cluster_id = current_cluster_id,
        cluster_metadata_column = cluster_metadata_column,
        cluster_color_map = specific_cluster_colors_map,
        point_size_factor = 2,
        image_alpha = 0.8,
        crop = FALSE,
        stroke = 0
      )
    },
    error = function(e) {
      message(
        "Plotting error for cluster ",
        current_cluster_id,
        ": ",
        e$message
      )
      return(NULL)
    }
  )
  
  if (!is.null(p_individual)) {
    cluster_highlight_plots[[current_cluster_id]] <- p_individual
  }
}


# Example: print the first highlighted cluster plot.
if (length(cluster_highlight_plots) > 0) {
  print(cluster_highlight_plots[[1]])
}


# ==============================================================================
# --- 6. Session information ---
# ==============================================================================

sessionInfo()