# ==============================================================================
# Public Human TB Granuloma - Spatial Feature Mapping
# ==============================================================================
#
# Purpose:
#   Map representative genes and cross-species conserved granuloma-associated
#   programs onto public human lung Mycobacterium tuberculosis granuloma
#   spatial transcriptomics data.
#
# Required input:
#   human_tb:
#     A processed Seurat spatial object generated by:
#       10_Public_Human_TB_Lung_Granuloma_ST_Analysis.R
#
# Main outputs generated in memory:
#   spatial_feature_plots
#   p_single_gene
#
# Notes:
#   This script does not save figures to disk.
#   Users can export plots as needed.
# ==============================================================================


# ==============================================================================
# --- 0. Load R packages ---
# ==============================================================================

suppressMessages({
  library(Seurat)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(scales)
  library(viridis)
  library(scico)
})

options(future.globals.maxSize = 9e10)
options(Seurat.object.assay.version = "v5")


# ==============================================================================
# --- 1. Example input object loading ---
# ==============================================================================

project_dir <- "path/to/project"

human_tb_object_path <- file.path(
  project_dir,
  "processed_objects",
  "public_human_TB_granuloma_processed.rds"
)

if (!exists("human_tb")) {
  human_tb <- readRDS(human_tb_object_path)
}

DefaultAssay(human_tb) <- "SCT"

message("Input object:")
print(human_tb)


# ==============================================================================
# --- 2. Define human TB granuloma gene programs for spatial mapping ---
# ==============================================================================

human_tb_gene_programs <- list(
  
  "Representative macrophage marker" = c(
    "MMP9"
  ),
  
  "Actin cytoskeleton and macrophage structural program" = c(
    "PDLIM4", "ARPC3", "EML4", "ACTR3", "PPP1R18",
    "ACTB", "INF2", "ACTN1", "ARPC5", "EFHD2", "MPP1",
    "ARHGEF1", "ARHGEF10L", "MYO1G", "CELSR1", "FMNL1",
    "TNS1", "VAV1", "ABR", "NCKAP1L", "PSTPIP1", "NCK2",
    "ARHGAP22", "HCLS1", "PDPN", "PTK2B", "VASP", "ARPC4",
    "RHOG", "ARPC1B", "RAP2A", "TSPAN3", "DOCK5", "RHOA",
    "MOB1A", "PARVB", "MYO1E", "TMSB4X", "TLN1", "EVL",
    "ARHGDIA", "ANXA11", "WASF2", "PTPRU", "ACTG1", "CD9",
    "CCDC88A", "PTPN12", "ARHGAP4", "ADGRE2", "APBB1IP",
    "FMNL3", "TUBB", "CLMN", "ARHGAP30", "CRYBG1",
    "EPB41L3", "ARPC2", "CD84", "GSN", "DOCK8", "WIPF1",
    "DIAPH1", "ARHGAP15", "PLEC", "PLXNA1", "RAP1A", "CRIP1",
    "FGD5", "CD38", "PARVG", "XPO6", "PDLIM7", "RACK1",
    "AFDN", "PLEKHO2"
  ),
  
  "Immune regulation and stress adaptation program extended" = c(
    "CSTA", "CSTB", "CST3", "SERPINE1", "SERPINB6", "SERPING1",
    "CAST", "LILRB4", "LILRB2", "PILRA", "TNIP1", "GPNMB",
    "IL18BP", "MT2A", "MT1X", "MT1G", "MT1H", "MT1E", "MT1F",
    "PIK3AP1", "PLD3", "SULT1C2", "BCL2A1", "GSTO1",
    "BHLHE41", "YWHAG", "NIBAN1", "NIBAN2", "BCL6", "TDP2",
    "CISH", "TAX1BP1", "GSR", "BCL2L1", "ALDH2", "CDA",
    "VNN2", "TGFBI", "SIGLEC10", "SIGLEC9", "YBX1", "PRDX1",
    "CIAO2A", "IGFLR1", "SELENON", "GLRX", "STEAP3", "APEX1",
    "CD47", "POLD4"
  ),
  
  "Metabolic adaptation program extended" = c(
    "IL4I1", "BCAT1", "PLIN2", "KYNU", "KMO", "ACSL1",
    "ALOX5AP", "ABCG1", "GYS1", "DPYD", "NME2", "GAA",
    "HAAO", "PYGL"
  ),
  
  "Broad transporter and ion channel program" = c(
    "SLC11A1", "CA12", "SLC6A8", "SLC5A3", "SLC16A3", "CA2",
    "SLC7A7", "SLC28A3", "SLC2A3", "AQP9", "KCNAB2",
    "SLC41A2", "SLC15A3", "CLIC1", "SLC43A3", "SLC3A2",
    "SLC2A5", "SLC31A1", "SLC39A14", "SLC25A6", "SLC16A1",
    "SLC38A6", "SLC20A1", "KCNN4", "KCNMB1", "ATOX1",
    "SLC26A6", "RHOQ", "SLC39A11", "SLC7A8", "SLC17A9",
    "KCTD7", "SLC6A6", "SLC30A1", "SLC15A4", "SLC31A2",
    "ATP5F1D", "SLC26A11", "SLC8A1", "SLC25A19", "SLC29A3",
    "KCNMA1", "SLC49A3", "SLC25A11", "SLC66A3", "SLC37A2",
    "SLC1A3", "SLC25A40", "SLC25A39", "SLC2A6", "SLC44A1",
    "SLC35E1", "SLC4A7", "SLC25A37", "SLC25A24", "SLC38A5",
    "SLC1A5", "SLC39A1", "SLC22A15", "SLC9A7", "SLC11A2",
    "SLC30A9", "SLC36A4", "SLC35B1", "FXYD2", "KCTD17",
    "SLC43A2", "KCTD12", "SLC12A7", "SLC2A9"
  ),
  
  "Cell junction program" = c(
    "CDH1", "JUP", "CTNNA1", "CTNNB1", "CTNND1",
    "CDH11", "DSC2", "DSG2", "PKP1", "PKP3",
    "PKP4", "DSP", "PERP", "CLDN5", "CLDN7",
    "CLDN11", "TJP1", "CGNL1", "GJA1", "GJA3",
    "GJA4", "GJA5", "GJA8", "GJA9", "GJA10",
    "GJB1", "GJB2", "GJB3", "GJB4", "GJB5",
    "GJB6", "GJB7", "GJC1", "GJC2", "GJC3",
    "GJD2", "GJD3", "GJD4", "GJE1"
  ),
  
  "Cytoskeletal architecture and repair program" = c(
    "KRT8", "KRT15", "KRT18", "KRT94", "KRT99",
    "EPPK1", "TCHH", "TGM5", "TGM1", "FLNB",
    "FLNC", "TAGLN", "POF1B", "TPM1", "CRIP1",
    "CRIP2", "NUDCD2", "AHNAK", "EZR", "EHD2",
    "STOML3", "AKAP2", "MPP6", "ANXA1", "ANXA2",
    "ANXA5", "ANXA11", "ANXA13", "S100A10", "S100A16",
    "S100A1", "CALM1", "CAPNS1", "CD38", "PLCD3",
    "ITPR1", "CHP1", "EFNB2", "PLEKHG5", "LIMK2",
    "CDC42EP3", "PPP2CB", "PPP1R27", "RND3", "PLEKHN1",
    "PMP22"
  ),
  
  "ECM remodeling and cell-matrix adhesion program" = c(
    "ERO1A", "P4HB", "CD44", "TNFAIP6", "FN1",
    "SDC2", "CAV1", "CAVIN1", "CAVIN2", "CD9",
    "CD81", "TSPAN8", "VWA7", "VWA11", "ANOS1",
    "APLP2", "PROM2", "MXRA8", "ITGA2", "ITGA3",
    "ITGA5", "ITGA6", "ITGAV", "ITGB1", "ITGB3",
    "ITGB4", "ITGB6", "ITGB8", "MMP2", "MMP9",
    "MMP15", "MMP19", "MMP14", "ADAM8", "ADAM11",
    "ELA1", "SERPINE1", "SERPINE2", "SERPINA1",
    "SERPINB1", "TIMP2", "TIMP3"
  ),
  
  "Fibroblast and ECM support program" = c(
    "COL1A1", "COL1A2", "COL4A1", "COL5A1", "COL5A2",
    "COL6A1", "COL6A2", "COL6A3", "FN1", "COL17A1",
    "MMP2", "MMP9", "SPARC", "DCN", "LUM",
    "PCOLCE", "P4HA1", "CCN1", "CCN2", "FSTL1",
    "NTD5", "ID3", "RBP4", "LOX", "BMP1",
    "ECM1", "PRELP", "HBEGF"
  ),
  
  "Immune regulation and tissue homeostasis program" = c(
    "CSTA", "CSTB", "CST3", "A2M", "CAST",
    "ARG1", "NFKBIA", "IL10", "TGFB1", "MCL1",
    "BCL2L1", "ENDOD1", "BABAM2", "YWHAB", "YWHAG",
    "NIBAN2", "RCAN1", "PKIG", "TSC22D1", "TSC22D2",
    "TSC22D3", "MT1A", "MT1B", "BHLHE40", "HIC1",
    "JUNB"
  ),
  
  "Transporter and channel program" = c(
    "AQP1", "RHBG", "ATP1A1", "ATP1B1", "SLC12A3",
    "KCNK5", "SLC12A7", "SLC9A3", "SLC9A3R1", "CHP1",
    "SLC20A1", "SLC39A8", "SLC6A14", "SLC38A2", "SLC1A5",
    "SLC1A3", "SLC15A2", "SLC6A6", "SLC6A8", "SLC13A5",
    "SLC5A8", "SLC23A2", "SLC28A1", "SLC25A5", "SLC10A3",
    "SLC25A55", "CA1", "CA2"
  ),
  
  "Metabolic adaptation program" = c(
    "SDHL", "IL4I1", "AASS", "SCCPDH", "GK",
    "ALOX15B", "FABP4", "FFAR2", "PLIN2", "GYG1",
    "CDA", "CKMT1A", "CKM", "NUDT4", "NDRG1",
    "NUPR1", "EGLN3", "ANGPTL4", "FLT1", "ACE",
    "EDN2", "VEGFA"
  ),
  
  "Oxidative phosphorylation program" = c(
    "MT-CO1", "MT-CO2", "MT-CO3", "COX4I1", "COX5A",
    "COX5B", "COX6A1", "COX6B1", "COX6C", "COX7A2",
    "COX7B", "COX7C", "COX8A", "COX10", "COX11",
    "COX15", "COX17", "CYCS", "UQCRQ", "MT-CYB",
    "MT-ND1", "MT-ND2", "MT-ND3", "MT-ND4", "MT-ND4L",
    "MT-ND5", "MT-ND6"
  ),
  
  "Retinoic-acid-associated program" = c(
    "ALDH1A1", "ALDH1A3", "CYP1B1", "CYP2S1", "CYP24A1",
    "CYP27A1", "RXRA", "RARB", "GPRC5C", "LRAT",
    "STRA6", "CRABP2"
  ),
  
  "Chemokine and lymphoid recruitment program" = c(
    "CCL11", "CCL15", "CCL17", "CCL18", "CCL19", "CCL2",
    "CCL20", "CCL21", "CCL23", "CCL24", "CCL3", "CCL5",
    "CCL8", "CCR1", "CXCL10", "CXCL11", "CXCL12", "CXCL13",
    "CXCL14", "CXCL16", "CXCL17", "CXCL2", "CXCL3", "CXCL5",
    "CXCL8", "CXCL9", "LTB", "TNFSF13", "TNFSF13B"
  ),
  
  "Selected upstream regulators" = c(
    "SPACA4", "ZAN", "WT1", "GATA6", "STAT6", "TEAD4", "JAG1"
  ),
  
  "Single gene GK5" = c(
    "GK5"
  )
)


# ==============================================================================
# --- 3. Helper functions ---
# ==============================================================================

filter_genes_present <- function(genes, object) {
  
  genes_present <- genes[genes %in% rownames(object)]
  genes_missing <- setdiff(genes, genes_present)
  
  if (length(genes_missing) > 0) {
    warning(
      "The following genes were not found and will be skipped: ",
      paste(genes_missing, collapse = ", ")
    )
  }
  
  return(genes_present)
}


make_spatial_feature_plots <- function(
    object,
    genes,
    program_name,
    image_alpha = 0,
    point_size_factor = 2,
    crop = FALSE,
    palette = c("scico_oslo", "viridis_plasma", "viridis_magma",
                "viridis_mako", "viridis_rocket", "viridis_turbo"),
    lower_limit = 0.5,
    upper_limit = NA_real_
) {
  
  palette <- match.arg(palette)
  
  genes_present <- filter_genes_present(
    genes = genes,
    object = object
  )
  
  if (length(genes_present) == 0) {
    warning("No valid genes for program: ", program_name)
    return(NULL)
  }
  
  plot_list <- list()
  
  for (gene in genes_present) {
    
    p <- SpatialFeaturePlot(
      object = object,
      features = gene,
      pt.size.factor = point_size_factor,
      image.alpha = image_alpha,
      crop = crop
    )
    
    if (palette == "scico_oslo") {
      p <- p +
        scale_fill_scico(
          palette = "oslo",
          direction = -1,
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_plasma") {
      p <- p +
        scale_fill_viridis(
          option = "plasma",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_magma") {
      p <- p +
        scale_fill_viridis(
          option = "magma",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_mako") {
      p <- p +
        scale_fill_viridis(
          option = "mako",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_rocket") {
      p <- p +
        scale_fill_viridis(
          option = "rocket",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_turbo") {
      p <- p +
        scale_fill_viridis(
          option = "turbo",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    p <- p +
      ggtitle(paste0(program_name, " - ", gene))
    
    plot_list[[gene]] <- p
  }
  
  return(plot_list)
}


# ==============================================================================
# --- 4. Select programs for spatial mapping ---
# ==============================================================================

# Default: selected upstream regulators.
# Replace this with any program name from human_tb_gene_programs.
selected_programs <- c(
  "Selected upstream regulators"
)

# To map all programs, use:
# selected_programs <- names(human_tb_gene_programs)

selected_programs <- intersect(
  selected_programs,
  names(human_tb_gene_programs)
)

if (length(selected_programs) == 0) {
  stop("No selected programs were found in human_tb_gene_programs.")
}


# ==============================================================================
# --- 5. Generate spatial feature plots ---
# ==============================================================================

spatial_feature_plots <- list()

for (program_name in selected_programs) {
  
  message("Generating spatial feature plots for: ", program_name)
  
  spatial_feature_plots[[program_name]] <- make_spatial_feature_plots(
    object = human_tb,
    genes = human_tb_gene_programs[[program_name]],
    program_name = program_name,
    image_alpha = 0,
    point_size_factor = 2,
    crop = FALSE,
    palette = "scico_oslo",
    lower_limit = 0.5,
    upper_limit = NA_real_
  )
}


# Example: print generated plots.
for (program_name in names(spatial_feature_plots)) {
  
  if (!is.null(spatial_feature_plots[[program_name]])) {
    
    for (gene in names(spatial_feature_plots[[program_name]])) {
      print(spatial_feature_plots[[program_name]][[gene]])
    }
  }
}


# ==============================================================================
# --- 6. Example single-gene spatial mapping ---
# ==============================================================================

single_gene <- "MMP9"

if (single_gene %in% rownames(human_tb)) {
  
  p_single_gene <- SpatialFeaturePlot(
    object = human_tb,
    features = single_gene,
    pt.size.factor = 0,
    image.alpha = 1,
    crop = FALSE
  ) +
    scale_fill_scico(
      palette = "oslo",
      direction = -1,
      limits = c(0.5, NA),
      oob = scales::squish
    ) +
    ggtitle(paste0("Human TB granuloma - ", single_gene))
  
  print(p_single_gene)
  
} else {
  warning("Gene not found: ", single_gene)
}


# ==============================================================================
# --- 7. Session information ---
# ==============================================================================

sessionInfo()