# ==============================================================================
# Head Kidney Granuloma - 2. Integrated Domain Annotation and E-Mac Refinement
# ==============================================================================
#
# Purpose:
#   Refine integrated spatial domains in the control-infected head kidney
#   BMKMANU S3000 spatial transcriptomics dataset.
#
# Main steps:
#   1. Use integrated clusters as the initial annotation backbone.
#   2. Align E-Mac domains from the infected-only spatial object to the integrated
#      control-infected object.
#   3. Refine Inner E-Mac and Outer E-Mac identities.
#   4. Remove residual unresolved integrated clusters.
#   5. Rename integrated clusters into biologically interpretable spatial domains.
#   6. Generate diagnostic UMAP, spatial, dot plot and cell/domain composition plots.
#   7. Extract macrophage-domain subset for downstream E-Mac comparisons.
#
# Required input objects:
#   seu_int_rpca:
#     Integrated control-infected head kidney spatial transcriptomics object
#     generated by 01_HK_ST_Control_Infected_RPCA_Integration.R.
#
#   TS_fliter:
#     Infected-only head kidney spatial transcriptomics object with annotated
#     domains, including Non-G Mac, Outer E-Mac and Inner E-Mac.
#
# Notes:
#   In this script, the original numeric integrated clusters are preserved as the
#   initial annotation. E-Mac labels are transferred using barcode overlap between
#   the infected-only object and the infected sample within the integrated object.
# ==============================================================================


# ==============================================================================
# --- 0. Load R packages ---
# ==============================================================================

suppressMessages({
  library(Seurat)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(RColorBrewer)
  library(scales)
  library(viridis)
})

options(future.globals.maxSize = 9e10)
options(Seurat.object.assay.version = "v5")


# ==============================================================================
# --- 1. Example input paths and object loading ---
# ==============================================================================

# Example project directory.
# Users should modify this path according to their local file organization.
project_dir <- "path/to/project"

# Example processed-object paths.
# These objects can also be generated directly from upstream scripts instead of
# being loaded from RDS files.
integrated_object_path <- file.path(
  project_dir,
  "processed_objects",
  "head_kidney_control_infected_RPCA_integrated_resolution0.60.rds"
)

infected_only_object_path <- file.path(
  project_dir,
  "processed_objects",
  "head_kidney_infected_only_ST_annotated.rds"
)

# Load objects if they are not already present in the R session.
if (!exists("seu_int_rpca")) {
  seu_int_rpca <- readRDS(integrated_object_path)
}

if (!exists("TS_fliter")) {
  TS_fliter <- readRDS(infected_only_object_path)
}

message("Integrated object:")
print(seu_int_rpca)

message("Infected-only object:")
print(TS_fliter)


# ==============================================================================
# --- 2. Initialize final annotation using integrated cluster IDs ---
# ==============================================================================

# Start from the original numeric integrated clusters.
# This preserves all integrated clusters before targeted E-Mac refinement.
seu_int_rpca$final_annot <- as.character(seu_int_rpca$seurat_clusters)

Idents(seu_int_rpca) <- "seurat_clusters"

message("Initial integrated clusters:")
print(table(Idents(seu_int_rpca), seu_int_rpca$orig.ident))


# ==============================================================================
# --- 3. Align E-Mac domains from infected-only object to integrated object ---
# ==============================================================================

# The integrated object contains the infected sample with a "_2" suffix after merge.
# Therefore, barcodes from the infected-only object are matched by appending "_2".
cells_inner_single <- paste0(
  WhichCells(TS_fliter, idents = "Inner E-Mac"),
  "_2"
)

cells_outer_single <- paste0(
  WhichCells(TS_fliter, idents = "Outer E-Mac"),
  "_2"
)

all_single_emac <- c(
  cells_inner_single,
  cells_outer_single
)

# Integrated clusters 7 and 15 were identified as candidate E-Mac-enriched
# regions in the integrated object.
cells_int_7_15 <- WhichCells(
  seu_int_rpca,
  idents = c("7", "15")
)

# Overlap between infected-only E-Mac annotations and integrated clusters 7/15.
intersection_inner <- intersect(
  cells_inner_single,
  cells_int_7_15
)

intersection_outer <- intersect(
  cells_outer_single,
  cells_int_7_15
)

# E-Mac spots detected in infected-only analysis but not assigned to integrated
# clusters 7/15.
only_in_single <- setdiff(
  all_single_emac,
  cells_int_7_15
)

# Spots assigned to integrated clusters 7/15 but not annotated as E-Macs in the
# infected-only analysis.
only_in_int <- setdiff(
  cells_int_7_15,
  all_single_emac
)

message("E-Mac barcode alignment summary:")
message("Inner E-Mac overlap: ", length(intersection_inner))
message("Outer E-Mac overlap: ", length(intersection_outer))
message("Only in infected-only E-Mac annotation: ", length(only_in_single))
message("Only in integrated clusters 7/15: ", length(only_in_int))


# ==============================================================================
# --- 4. Targeted identity refinement ---
# ==============================================================================

# 4.1 High-confidence overlap spots are directly assigned as Inner or Outer E-Macs.
seu_int_rpca$final_annot[intersection_inner] <- "Inner E-Mac"
seu_int_rpca$final_annot[intersection_outer] <- "Outer E-Mac"

# 4.2 E-Mac spots present in infected-only analysis but not in integrated clusters
#     7/15 are assigned to Outer E-Mac.
seu_int_rpca$final_annot[only_in_single] <- "Outer E-Mac"

# 4.3 Spots present in integrated clusters 7/15 but not annotated as E-Macs in the
#     infected-only analysis are reassigned according to their infected-only labels.
target_mapping <- c(
  "Eryt"       = "2",
  "Gran"       = "1",
  "Non-G Mac"  = "0",
  "B"          = "12",
  "T-B-APCs"   = "4",
  "Fibro-Endo" = "11"
)

# Remove "_2" suffix and query the infected-only object for original labels.
intruders_clean <- gsub(
  pattern = "_2$",
  replacement = "",
  x = only_in_int
)

intruders_orig <- as.character(
  Idents(TS_fliter)[intruders_clean]
)

for (i in seq_along(only_in_int)) {
  barcode <- only_in_int[i]
  orig_id <- intruders_orig[i]
  
  if (!is.na(orig_id) && orig_id %in% names(target_mapping)) {
    seu_int_rpca$final_annot[barcode] <- target_mapping[[orig_id]]
  }
}

Idents(seu_int_rpca) <- "final_annot"

message("After targeted E-Mac refinement:")
print(table(Idents(seu_int_rpca), seu_int_rpca$orig.ident))


# ==============================================================================
# --- 5. Remove unresolved residual clusters 7 and 15 ---
# ==============================================================================

# After targeted reassignment, residual spots still labeled as 7 or 15 are removed.
# These spots were not confidently assigned to E-Mac or other major domains.
cells_to_remove <- WhichCells(
  seu_int_rpca,
  idents = c("7", "15")
)

message("Number of residual spots to remove: ", length(cells_to_remove))

cells_to_keep <- setdiff(
  Cells(seu_int_rpca),
  cells_to_remove
)

seu_int_rpca <- subset(
  seu_int_rpca,
  cells = cells_to_keep
)

seu_int_rpca$final_annot <- droplevels(
  factor(seu_int_rpca$final_annot)
)

Idents(seu_int_rpca) <- "final_annot"

message("After removing residual clusters 7 and 15:")
print(table(Idents(seu_int_rpca), seu_int_rpca$orig.ident))


# ==============================================================================
# --- 6. Rename refined clusters into biological domain labels ---
# ==============================================================================

new_cluster_names <- c(
  "0"  = "Mac (Infection-associated)",
  "1"  = "Gran (Infection-associated)",
  "2"  = "Eryt",
  "8"  = "Eryt",
  "3"  = "Mac (Homeostatic)",
  "5"  = "Mac (Homeostatic)",
  "4"  = "Lymphocyte",
  "6"  = "Gran (Homeostatic)",
  "9"  = "Gran (Homeostatic)",
  "10" = "Gran-Eryt (Homeostatic)",
  "11" = "Vascular niche (Fibro-mixed)",
  "12" = "B (Homeostatic)",
  "13" = "B (Homeostatic)",
  "14" = "Eryt (Intravascular)",
  "Inner E-Mac" = "Inner E-Mac",
  "Outer E-Mac" = "Outer E-Mac"
)

seu_int_rpca <- RenameIdents(
  object = seu_int_rpca,
  new_cluster_names
)

desired_order <- c(
  "Eryt",
  "Eryt (Intravascular)",
  "Gran-Eryt (Homeostatic)",
  "Gran (Homeostatic)",
  "Gran (Infection-associated)",
  "Mac (Homeostatic)",
  "Mac (Infection-associated)",
  "Outer E-Mac",
  "Inner E-Mac",
  "B (Homeostatic)",
  "Lymphocyte",
  "Vascular niche (Fibro-mixed)"
)

seu_int_rpca <- SetIdent(
  object = seu_int_rpca,
  value = factor(
    Idents(seu_int_rpca),
    levels = desired_order
  )
)

# Store final domain labels in metadata.
seu_int_rpca$annotated_cluster <- Idents(seu_int_rpca)

message("Final annotated clusters:")
print(table(Idents(seu_int_rpca), seu_int_rpca$orig.ident))


# ==============================================================================
# --- 7. Color scheme setup ---
# ==============================================================================

cluster_colors <- c(
  "Eryt"                              = "pink",
  "Eryt (Intravascular)"              = "#CC79A7",
  "Gran-Eryt (Homeostatic)"           = "#FFFFCC",
  "Gran (Homeostatic)"                = "#FFDBB7",
  "Gran (Infection-associated)"       = "#FFBA75",
  "Mac (Homeostatic)"                 = "#4169E1",
  "Mac (Infection-associated)"        = "#000080",
  "Outer E-Mac"                       = "grey",
  "Inner E-Mac"                       = "#CAFCFE",
  "B (Homeostatic)"                   = "#A6CEE3",
  "Lymphocyte"                        = "red",
  "Vascular niche (Fibro-mixed)"      = "#8B4513"
)

color_prgn <- colorRampPalette(
  rev(brewer.pal(n = 11, name = "PRGn"))
)(100)


# ==============================================================================
# --- 8. UMAP and spatial visualization of annotated domains ---
# ==============================================================================

# UMAP split by sample.
p_umap_split_annotated <- DimPlot(
  object = seu_int_rpca,
  reduction = "umap",
  label = FALSE,
  pt.size = 0.3,
  raster = FALSE,
  split.by = "orig.ident"
) &
  theme(legend.title = element_blank()) &
  scale_color_manual(values = cluster_colors)

print(p_umap_split_annotated)


# UMAP of all spatial units.
p_umap_annotated <- DimPlot(
  object = seu_int_rpca,
  reduction = "umap",
  label = FALSE,
  pt.size = 0.3,
  raster = FALSE
) &
  theme(legend.title = element_blank()) &
  scale_color_manual(values = cluster_colors)

print(p_umap_annotated)


# UMAP colored by condition.
p_umap_condition <- DimPlot(
  object = seu_int_rpca,
  reduction = "umap",
  group.by = "condition",
  pt.size = 0.3,
  raster = TRUE
)

print(p_umap_condition)


# Spatial visualization of final annotated domains.
p_spatial_annotated <- SpatialDimPlot(
  object = seu_int_rpca,
  label = FALSE,
  label.size = 6,
  image.alpha = 0,
  pt.size.factor = 4.0,
  crop = FALSE
) &
  guides(fill = guide_legend(override.aes = list(size = 4))) &
  theme(legend.title = element_blank()) &
  scale_fill_manual(values = cluster_colors)

print(p_spatial_annotated)


# ==============================================================================
# --- 9. Marker gene DotPlot for final domain annotation ---
# ==============================================================================

DefaultAssay(seu_int_rpca) <- "SCT"

marker_list <- list(
  "Eryt" = c(
    "LOC119891533", "slc4a1a", "alas2", "fech", "slc25a37", "sptb"
  ),
  
  "Gran" = c(
    "LOC119914447", "LOC119900902", "LOC119889900",
    "mmp9", "LOC119900132", "LOC119891034"
  ),
  
  "Antigen Processing & Presentation" = c(
    "LOC119888605", "LOC119917015", "LOC119912422",
    "LOC119884279", "LOC119918458", "ifi30", "cd83", "cd40"
  ),
  
  "Mac" = c(
    "csf1rb", "marco", "mrc1b", "LOC119891768",
    "si-ch211-212k18.7", "LOC119894959", "LOC119883615"
  ),
  
  "E-Mac" = c(
    "LOC119917376", "jupa", "LOC119889888", "dspa",
    "LOC119902058", "LOC119917243", "dsc2l",
    "LOC119900663", "cldn11a", "LOC119908668", "LOC119908847"
  ),
  
  "B" = c(
    "LOC119890508", "LOC119890540", "LOC119890555", "LOC119890570",
    "ebf1a", "sox4b", "LOC119882634", "cd79a",
    "LOC119884751", "LOC119897215"
  ),
  
  "T" = c(
    "LOC119903450", "LOC119883393", "LOC119883434",
    "LOC119897409", "LOC119897410",
    "cd8a", "cd8b", "lck", "LOC119900445"
  ),
  
  "Vascular niche" = c(
    "col1a1a", "col1a1b", "col1a2",
    "col6a1", "sparc", "LOC119882173"
  )
)

p_marker_dotplot <- DotPlot(
  object = seu_int_rpca,
  features = marker_list
) +
  scale_color_gradientn(colors = color_prgn) +
  labs(
    x = "Cell Clusters",
    y = "Marker Genes",
    color = "Avg Expression",
    size = "Percent Expressed"
  ) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      vjust = 1,
      size = 9,
      face = "bold"
    ),
    axis.text.y = element_text(
      size = 9,
      face = "italic"
    ),
    axis.title = element_text(
      size = 10,
      face = "bold"
    ),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    panel.grid = element_blank(),
    legend.position = "right"
  )

print(p_marker_dotplot)


# ==============================================================================
# --- 10. Cell/domain composition calculation and visualization ---
# ==============================================================================

cell_table <- table(
  CellType = Idents(seu_int_rpca),
  Sample = seu_int_rpca$orig.ident
)

cell_ratio <- prop.table(
  cell_table,
  margin = 2
) %>%
  as.data.frame()

colnames(cell_ratio) <- c(
  "CellType",
  "Sample",
  "Freq"
)

cell_counts <- as.data.frame(cell_table)
colnames(cell_counts) <- c(
  "CellType",
  "Sample",
  "Count"
)

cell_ratio <- merge(
  cell_ratio,
  cell_counts,
  by = c("CellType", "Sample")
)

cell_ratio$CellType <- factor(
  cell_ratio$CellType,
  levels = desired_order
)

cell_ratio <- cell_ratio %>%
  arrange(Sample, CellType)

cell_ratio$LegendLabel <- paste0(
  cell_ratio$CellType,
  " (",
  sprintf("%.1f%%", cell_ratio$Freq * 100),
  ", ",
  cell_ratio$Count,
  ")"
)

p_cell_composition_pie <- ggplot(
  cell_ratio,
  aes(x = "", y = Freq, fill = CellType)
) +
  geom_bar(
    stat = "identity",
    width = 1,
    color = "white"
  ) +
  coord_polar(theta = "y") +
  facet_wrap(~ Sample, nrow = 1) +
  scale_fill_manual(
    values = cluster_colors,
    labels = cell_ratio$LegendLabel
  ) +
  theme_void() +
  labs(
    fill = "Cell Type (Ratio, Count)",
    title = "Cell Composition per Sample"
  ) +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 11),
    legend.text = element_text(size = 9),
    plot.title = element_text(hjust = 0.5)
  )

print(p_cell_composition_pie)


# ==============================================================================
# --- 11. Extract macrophage-domain subset for downstream E-Mac analyses ---
# ==============================================================================

cell_groups_to_compare <- c(
  "Mac (Infection-associated)",
  "Outer E-Mac",
  "Inner E-Mac"
)

cells_to_plot <- WhichCells(
  object = seu_int_rpca,
  idents = cell_groups_to_compare
)

object_sub <- subset(
  x = seu_int_rpca,
  cells = cells_to_plot
)

message("Macrophage-domain subset:")
print(table(Idents(object_sub), object_sub$orig.ident))


# ==============================================================================
# --- 12. Session information ---
# ==============================================================================

sessionInfo()