# ==============================================================================
# Head Kidney Granuloma - 3. Differential Expression and Cluster Correlation
# ==============================================================================
#
# Purpose:
#   Identify marker genes for annotated spatial domains in the integrated
#   control-infected head kidney spatial transcriptomics dataset, calculate
#   average expression profiles, and assess inter-domain transcriptional
#   correlations.
#
# Required input:
#   seu_int_rpca:
#     Integrated and annotated Seurat object generated by:
#       01_HK_ST_Control_Infected_RPCA_Integration.R
#       02_HK_ST_Integrated_Domain_Annotation.R
#
# Main outputs generated in memory:
#   all_markers
#   significant_markers
#   top20_markers
#   cluster_avg_exp
#   diff_gene_exp
#   cor_matrix
#   p_cluster_correlation
#
# Notes:
#   This script does not write files to disk. Users can export objects as needed.
# ==============================================================================


# ==============================================================================
# --- 0. Load R packages ---
# ==============================================================================

suppressMessages({
  library(Seurat)
  library(dplyr)
  library(tibble)
  library(ggplot2)
  library(pheatmap)
  library(RColorBrewer)
  library(scales)
  library(Matrix)
})

options(future.globals.maxSize = 9e10)
options(Seurat.object.assay.version = "v5")


# ==============================================================================
# --- 1. Example input object loading ---
# ==============================================================================

# Example project directory.
# Users should modify this path according to their local file organization.
project_dir <- "path/to/project"

# Example processed object path.
annotated_object_path <- file.path(
  project_dir,
  "processed_objects",
  "head_kidney_control_infected_RPCA_integrated_annotated.rds"
)

# Load object if it is not already present in the R session.
if (!exists("seu_int_rpca")) {
  seu_int_rpca <- readRDS(annotated_object_path)
}

message("Input object:")
print(seu_int_rpca)

message("Current identity classes:")
print(table(Idents(seu_int_rpca), seu_int_rpca$orig.ident))


# ==============================================================================
# --- 2. Prepare SCT assay for differential expression ---
# ==============================================================================

DefaultAssay(seu_int_rpca) <- "SCT"

# For SCT-based differential expression, PrepSCTFindMarkers is recommended
# when multiple SCT models are present.
seu_int_rpca <- PrepSCTFindMarkers(seu_int_rpca)

message("SCT assay prepared for marker gene identification.")


# ==============================================================================
# --- 3. Identify marker genes for all annotated spatial domains ---
# ==============================================================================

all_markers <- FindAllMarkers(
  object = seu_int_rpca,
  assay = "SCT",
  only.pos = TRUE,
  min.pct = 0.10,
  logfc.threshold = 0.25,
  test.use = "wilcox",
  verbose = TRUE
)

if (nrow(all_markers) == 0) {
  warning("No marker genes were identified. Consider adjusting min.pct or logfc.threshold.")
} else {
  message("Number of marker genes identified: ", nrow(all_markers))
}

# Significant marker genes.
# The threshold here follows the exploratory analysis used in the manuscript code.
significant_markers <- all_markers %>%
  filter(p_val_adj < 0.10)

message("Number of significant marker genes: ", nrow(significant_markers))


# ==============================================================================
# --- 4. Extract top marker genes per spatial domain ---
# ==============================================================================

top20_markers <- all_markers %>%
  group_by(cluster) %>%
  slice_max(
    order_by = avg_log2FC,
    n = 20,
    with_ties = FALSE
  ) %>%
  ungroup()

message("Top 20 markers per cluster/domain extracted.")


# ==============================================================================
# --- 5. Average expression by annotated spatial domain ---
# ==============================================================================

cluster_avg_exp <- AverageExpression(
  object = seu_int_rpca,
  assays = "SCT",
  slot = "data"
)

# Matrix of average expression values.
cluster_avg_exp_matrix <- cluster_avg_exp$SCT

message("Average expression matrix:")
print(dim(cluster_avg_exp_matrix))


# ==============================================================================
# --- 6. Average expression matrix for significant marker genes ---
# ==============================================================================

common_genes <- intersect(
  unique(significant_markers$gene),
  rownames(cluster_avg_exp_matrix)
)

if (length(common_genes) > 0) {
  diff_gene_exp <- cluster_avg_exp_matrix[common_genes, , drop = FALSE]
} else {
  diff_gene_exp <- NULL
  warning("No overlapping genes between significant markers and average expression matrix.")
}

if (!is.null(diff_gene_exp)) {
  message("Differential marker average-expression matrix:")
  print(dim(diff_gene_exp))
}


# ==============================================================================
# --- 7. Cluster/domain correlation analysis ---
# ==============================================================================

# Pearson correlation based on average SCT expression across annotated domains.
cor_matrix <- cor(
  as.matrix(cluster_avg_exp_matrix),
  method = "pearson",
  use = "pairwise.complete.obs"
)

# Color scale used for the heatmap.
color_prgn <- colorRampPalette(
  rev(brewer.pal(n = 11, name = "PRGn"))
)(100)

# Correlation values are usually high across related spatial domains.
# This range can be adjusted according to the distribution of cor_matrix.
cor_breaks <- seq(
  from = 0.5,
  to = 1,
  length.out = 101
)

p_cluster_correlation <- pheatmap(
  mat = cor_matrix,
  color = color_prgn,
  breaks = cor_breaks,
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  show_rownames = TRUE,
  show_colnames = TRUE,
  main = "Cluster Correlation Heatmap (SCT Data)",
  silent = TRUE
)

print(p_cluster_correlation)


# ==============================================================================
# --- 8. Optional pairwise differential expression between selected domains ---
# ==============================================================================

# This helper function performs pairwise differential expression only when
# both identities are present in the object.
run_pairwise_DEG <- function(
    object,
    ident_1,
    ident_2,
    assay = "SCT",
    min_pct = 0.10,
    logfc_threshold = 0.20,
    padj_threshold = 0.10
) {
  
  current_idents <- levels(Idents(object))
  
  if (!ident_1 %in% current_idents) {
    warning("ident_1 not found: ", ident_1)
    return(NULL)
  }
  
  if (!ident_2 %in% current_idents) {
    warning("ident_2 not found: ", ident_2)
    return(NULL)
  }
  
  markers <- FindMarkers(
    object = object,
    ident.1 = ident_1,
    ident.2 = ident_2,
    assay = assay,
    only.pos = FALSE,
    min.pct = min_pct,
    test.use = "wilcox",
    logfc.threshold = logfc_threshold,
    verbose = TRUE
  )
  
  markers <- markers %>%
    rownames_to_column("gene") %>%
    mutate(
      ident_1 = ident_1,
      ident_2 = ident_2,
      contrast = paste0(ident_1, " vs ", ident_2),
      significant = p_val_adj < padj_threshold
    )
  
  return(markers)
}


# Example pairwise comparisons based on final annotated domains.
# Modify these labels according to levels(Idents(seu_int_rpca)).
deg_gran_infection_vs_homeostatic <- run_pairwise_DEG(
  object = seu_int_rpca,
  ident_1 = "Gran (Infection-associated)",
  ident_2 = "Gran (Homeostatic)"
)

deg_mac_infection_vs_homeostatic <- run_pairwise_DEG(
  object = seu_int_rpca,
  ident_1 = "Mac (Infection-associated)",
  ident_2 = "Mac (Homeostatic)"
)

deg_outer_emac_vs_mac <- run_pairwise_DEG(
  object = seu_int_rpca,
  ident_1 = "Outer E-Mac",
  ident_2 = "Mac (Infection-associated)"
)

deg_inner_emac_vs_mac <- run_pairwise_DEG(
  object = seu_int_rpca,
  ident_1 = "Inner E-Mac",
  ident_2 = "Mac (Infection-associated)"
)


# Combine pairwise DEG results if available.
pairwise_deg_list <- list(
  Gran_infection_vs_homeostatic = deg_gran_infection_vs_homeostatic,
  Mac_infection_vs_homeostatic  = deg_mac_infection_vs_homeostatic,
  Outer_EMac_vs_Mac             = deg_outer_emac_vs_mac,
  Inner_EMac_vs_Mac             = deg_inner_emac_vs_mac
)

pairwise_deg_results <- bind_rows(
  pairwise_deg_list,
  .id = "comparison_name"
)

message("Pairwise DEG results:")
print(table(pairwise_deg_results$comparison_name, pairwise_deg_results$significant))


# ==============================================================================
# --- 9. Optional infection-control comparison within each annotated domain ---
# ==============================================================================

# This section compares Treat vs Control within the same annotated domain.
# It is only meaningful for domains that contain spatial units from both conditions.

seu_int_rpca$cell_type_group <- paste(
  seu_int_rpca$annotated_cluster,
  seu_int_rpca$orig.ident,
  sep = "_"
)

Idents(seu_int_rpca) <- "cell_type_group"

message("Available cell_type_group identities:")
print(table(Idents(seu_int_rpca)))


run_condition_DEG_within_domain <- function(
    object,
    domain,
    condition_1 = "Treat",
    condition_2 = "Control",
    assay = "SCT",
    min_pct = 0.10,
    logfc_threshold = 0.20,
    padj_threshold = 0.10
) {
  
  ident_1 <- paste(domain, condition_1, sep = "_")
  ident_2 <- paste(domain, condition_2, sep = "_")
  
  current_idents <- levels(Idents(object))
  
  if (!ident_1 %in% current_idents || !ident_2 %in% current_idents) {
    warning(
      "Skipping domain because one or both condition-specific identities are missing: ",
      domain
    )
    return(NULL)
  }
  
  markers <- FindMarkers(
    object = object,
    ident.1 = ident_1,
    ident.2 = ident_2,
    assay = assay,
    only.pos = FALSE,
    min.pct = min_pct,
    test.use = "wilcox",
    logfc.threshold = logfc_threshold,
    verbose = TRUE
  )
  
  markers <- markers %>%
    rownames_to_column("gene") %>%
    mutate(
      domain = domain,
      ident_1 = ident_1,
      ident_2 = ident_2,
      contrast = paste0(ident_1, " vs ", ident_2),
      significant = p_val_adj < padj_threshold
    )
  
  return(markers)
}


# Run Treat vs Control comparison for domains that contain both conditions.
domains_to_compare <- unique(as.character(seu_int_rpca$annotated_cluster))

condition_deg_results <- lapply(
  domains_to_compare,
  function(domain_i) {
    run_condition_DEG_within_domain(
      object = seu_int_rpca,
      domain = domain_i,
      condition_1 = "Treat",
      condition_2 = "Control"
    )
  }
)

names(condition_deg_results) <- domains_to_compare

condition_deg_results <- bind_rows(
  condition_deg_results,
  .id = "domain_name"
)

message("Condition-specific DEG results:")
if (nrow(condition_deg_results) > 0) {
  print(table(condition_deg_results$domain_name, condition_deg_results$significant))
} else {
  message("No condition-specific DEG results were generated.")
}

# Switch identities back to annotated clusters after condition-specific DEG analysis.
Idents(seu_int_rpca) <- "annotated_cluster"


# ==============================================================================
# --- 10. Optional analysis using Spatial assay raw counts or log-normalized data ---
# ==============================================================================

# In some cases, marker analysis may also be performed on the original Spatial
# assay after log-normalization. This is provided as an optional alternative and
# is not required if SCT-based results are used.

run_spatial_assay_marker_analysis <- FALSE

if (run_spatial_assay_marker_analysis) {
  
  DefaultAssay(seu_int_rpca) <- "Spatial"
  
  seu_int_rpca <- NormalizeData(
    object = seu_int_rpca,
    assay = "Spatial"
  )
  
  spatial_markers <- FindAllMarkers(
    object = seu_int_rpca,
    assay = "Spatial",
    slot = "data",
    only.pos = TRUE,
    min.pct = 0.10,
    test.use = "wilcox",
    logfc.threshold = 0.20
  )
  
  spatial_significant_markers <- spatial_markers %>%
    filter(p_val_adj < 0.10)
  
  spatial_cluster_avg_counts <- AverageExpression(
    object = seu_int_rpca,
    assays = "Spatial",
    slot = "counts"
  )
  
  DefaultAssay(seu_int_rpca) <- "SCT"
}


# ==============================================================================
# --- 11. Session information ---
# ==============================================================================

sessionInfo()