# ==============================================================================
# Head Kidney Granuloma - 4. Functional Program DotPlots
# ==============================================================================
#
# Purpose:
#   Generate DotPlots for functional gene programs across annotated spatial
#   domains in the integrated head kidney spatial transcriptomics dataset.
#
# Required input:
#   seu_int_rpca:
#     Integrated and annotated Seurat object generated by:
#       01_HK_ST_Control_Infected_RPCA_Integration.R
#       02_HK_ST_Integrated_Domain_Annotation.R
#
# Main outputs generated in memory:
#   program_dotplots
#     A named list containing DotPlot objects for all spatial domains and,
#     where applicable, macrophage-related domains.
#
# Notes:
#   This script does not save figures to disk. Users can export plots as needed.
# ==============================================================================


# ==============================================================================
# --- 0. Load R packages ---
# ==============================================================================

suppressMessages({
  library(Seurat)
  library(ggplot2)
  library(dplyr)
  library(viridis)
  library(RColorBrewer)
  library(scales)
})

options(future.globals.maxSize = 9e10)
options(Seurat.object.assay.version = "v5")


# ==============================================================================
# --- 1. Example input object loading ---
# ==============================================================================

project_dir <- "path/to/project"

annotated_object_path <- file.path(
  project_dir,
  "processed_objects",
  "head_kidney_control_infected_RPCA_integrated_annotated.rds"
)

if (!exists("seu_int_rpca")) {
  seu_int_rpca <- readRDS(annotated_object_path)
}

DefaultAssay(seu_int_rpca) <- "SCT"

message("Input object:")
print(seu_int_rpca)

message("Current identity classes:")
print(table(Idents(seu_int_rpca), seu_int_rpca$orig.ident))


# ==============================================================================
# --- 2. Extract macrophage-related spatial domains ---
# ==============================================================================

cell_groups_to_compare <- c(
  "Mac (Homeostatic)",
  "Mac (Infection-associated)",
  "Outer E-Mac",
  "Inner E-Mac"
)

missing_groups <- setdiff(
  cell_groups_to_compare,
  levels(Idents(seu_int_rpca))
)

if (length(missing_groups) > 0) {
  warning(
    "The following macrophage-related groups are not present in the object: ",
    paste(missing_groups, collapse = ", ")
  )
}

cell_groups_to_compare <- intersect(
  cell_groups_to_compare,
  levels(Idents(seu_int_rpca))
)

cells_to_plot <- WhichCells(
  object = seu_int_rpca,
  idents = cell_groups_to_compare
)

object_sub <- subset(
  x = seu_int_rpca,
  cells = cells_to_plot
)

message("Macrophage-related subset:")
print(table(Idents(object_sub), object_sub$orig.ident))


# ==============================================================================
# --- 3. Helper functions for DotPlot generation ---
# ==============================================================================

filter_marker_list <- function(marker_list, object, program_name = "program") {
  
  filtered_list <- lapply(marker_list, function(genes) {
    genes[genes %in% rownames(object)]
  })
  
  filtered_list <- filtered_list[lengths(filtered_list) > 0]
  
  requested_genes <- unique(unlist(marker_list))
  present_genes <- unique(unlist(filtered_list))
  missing_genes <- setdiff(requested_genes, present_genes)
  
  if (length(missing_genes) > 0) {
    warning(
      "Missing genes in ", program_name, ": ",
      paste(missing_genes, collapse = ", ")
    )
  }
  
  return(filtered_list)
}


add_dotplot_style <- function(
    p,
    palette_type = c("viridis", "gradient"),
    viridis_option = "viridis",
    gradient_colors = NULL,
    color_limits = NULL,
    size_range = c(-1.2, 7.5),
    size_limits = c(0, 100),
    size_breaks = c(25, 50, 75)
) {
  
  palette_type <- match.arg(palette_type)
  
  p <- p +
    scale_size_continuous(
      range = size_range,
      limits = size_limits,
      breaks = size_breaks
    ) +
    labs(
      x = NULL,
      y = NULL,
      color = NULL,
      size = NULL
    ) +
    theme(
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        vjust = 1,
        size = 9,
        face = "bold"
      ),
      axis.text.y = element_text(
        size = 9,
        face = "italic"
      ),
      axis.title = element_text(
        size = 10,
        face = "bold"
      ),
      legend.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      panel.grid = element_blank(),
      legend.position = "right"
    )
  
  if (palette_type == "viridis") {
    if (is.null(color_limits)) {
      p <- p + scale_color_viridis(option = viridis_option)
    } else {
      p <- p + scale_color_viridis(
        option = viridis_option,
        limits = color_limits,
        oob = scales::squish
      )
    }
  }
  
  if (palette_type == "gradient") {
    if (is.null(gradient_colors)) {
      stop("gradient_colors must be provided when palette_type = 'gradient'.")
    }
    
    if (is.null(color_limits)) {
      p <- p + scale_color_gradientn(colors = gradient_colors)
    } else {
      p <- p + scale_color_gradientn(
        colors = gradient_colors,
        limits = color_limits,
        oob = scales::squish
      )
    }
  }
  
  return(p)
}


make_program_dotplots <- function(
    program_name,
    marker_list,
    object_all,
    object_subset = NULL,
    palette_type = c("viridis", "gradient"),
    viridis_option = "viridis",
    gradient_colors = NULL,
    all_color_limits = NULL,
    subset_color_limits = c(-1.2, 1.0),
    all_size_range = c(-1.2, 7.5),
    subset_size_range = c(-1.1, 8)
) {
  
  palette_type <- match.arg(palette_type)
  
  marker_list_all <- filter_marker_list(
    marker_list = marker_list,
    object = object_all,
    program_name = paste0(program_name, " - all domains")
  )
  
  p_all <- DotPlot(
    object = object_all,
    features = marker_list_all
  )
  
  p_all <- add_dotplot_style(
    p = p_all,
    palette_type = palette_type,
    viridis_option = viridis_option,
    gradient_colors = gradient_colors,
    color_limits = all_color_limits,
    size_range = all_size_range
  )
  
  plot_list <- list(
    all_domains = p_all
  )
  
  if (!is.null(object_subset)) {
    
    marker_list_subset <- filter_marker_list(
      marker_list = marker_list,
      object = object_subset,
      program_name = paste0(program_name, " - macrophage domains")
    )
    
    p_subset <- DotPlot(
      object = object_subset,
      features = marker_list_subset
    )
    
    p_subset <- add_dotplot_style(
      p = p_subset,
      palette_type = palette_type,
      viridis_option = viridis_option,
      gradient_colors = gradient_colors,
      color_limits = subset_color_limits,
      size_range = subset_size_range
    )
    
    plot_list$macrophage_domains <- p_subset
  }
  
  return(plot_list)
}


program_dotplots <- list()


# ==============================================================================
# --- 4. Cell junction program ---
# ==============================================================================

marker_cell_junction <- list(
  "AJ" = c(
    "LOC119917376", "cdh11", "jupa", "ctnna1", "ctnnd1"
  ),
  "DSM" = c(
    "dsc2l", "LOC119902058", "LOC119905441",
    "LOC119889888", "dspa", "LOC119917243"
  ),
  "TJ" = c(
    "cldn5a", "LOC119900663", "cldn11a", "tjp1a", "cgnl1"
  ),
  "GJ" = c(
    "LOC119908847", "LOC119908668"
  )
)

program_dotplots$cell_junction <- make_program_dotplots(
  program_name = "Cell junction program",
  marker_list = marker_cell_junction,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "viridis",
  viridis_option = "magma",
  subset_color_limits = c(-1.2, 1.0)
)

print(program_dotplots$cell_junction$all_domains)
print(program_dotplots$cell_junction$macrophage_domains)


# ==============================================================================
# --- 5. Cytoskeletal architecture and regulatory program ---
# ==============================================================================

marker_cytoskeleton <- list(
  "Keratin Cytoskeleton" = c(
    "LOC119905733", "LOC119886877", "krt15", "krt94",
    "krt99", "eppk1", "LOC119912524", "LOC119886962", "tgm1l1"
  ),
  
  "Actin Cytoskeleton & Organization" = c(
    "LOC119885789", "LOC119909726", "pof1b",
    "LOC119901854", "crip1", "crip2", "nudcd2"
  ),
  
  "Membrane-Cytoskeleton Coupling & Repair" = c(
    "ahnak", "LOC119909740", "ezrb", "ehd2b", "stoml3b",
    "LOC119914141", "mpp6b", "anxa1a", "LOC119888099",
    "anxa2a", "LOC119890527", "LOC119898827", "anxa11a"
  ),
  
  "Calcium Signaling" = c(
    "s100a10a", "si-ch211-105c13.3", "s100v2",
    "capns1b", "LOC119912040", "LOC119915637", "LOC119886455"
  ),
  
  "Rho GTPase Signaling" = c(
    "efnb2a", "plekhg5b", "limk2", "cdc42ep3",
    "ppp2cab", "ppp1r27b", "rnd3a", "plekhn1", "LOC119890724"
  )
)

program_dotplots$cytoskeleton <- make_program_dotplots(
  program_name = "Cytoskeletal architecture and regulatory program",
  marker_list = marker_cytoskeleton,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "viridis",
  viridis_option = "viridis",
  subset_color_limits = c(-1.2, 1.0)
)

print(program_dotplots$cytoskeleton$all_domains)
print(program_dotplots$cytoskeleton$macrophage_domains)


# ==============================================================================
# --- 6. Extracellular matrix remodeling program ---
# ==============================================================================

marker_ecm <- list(
  "ECM Proteases" = c(
    "mmp2", "mmp15b", "mmp19", "adam11", "LOC119886402"
  ),
  
  "ECM Proteolysis Inhibitors" = c(
    "serpine1", "serpine2", "LOC119908472",
    "LOC119906979", "LOC119918277"
  ),
  
  "Cell-Matrix Adhesion & Transmembrane Anchorage" = c(
    "ero1a", "p4hb", "cd44b", "tnfaip6", "fn1a", "fn1b",
    "LOC119897849", "cav1", "cavin1b", "LOC119907497",
    "LOC119918071", "cd81a", "LOC119893200", "LOC119895007",
    "LOC119899685", "vwa11", "anos1b", "aplp2", "prom2",
    "LOC119886359"
  ),
  
  "Integrins" = c(
    "itga3b", "itga5", "LOC119902203", "itgav",
    "LOC119892793", "LOC119915730", "itgb6"
  )
)

program_dotplots$ecm_remodeling <- make_program_dotplots(
  program_name = "Extracellular matrix remodeling program",
  marker_list = marker_ecm,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "viridis",
  viridis_option = "mako",
  subset_color_limits = c(-1.2, 1.0)
)

print(program_dotplots$ecm_remodeling$all_domains)
print(program_dotplots$ecm_remodeling$macrophage_domains)


# ==============================================================================
# --- 7. Potential regulatory program ---
# ==============================================================================

marker_regulatory <- list(
  "Potential membrane microdomain organizers" = c(
    "spaca4l", "LOC119906807", "zanl"
  ),
  
  "Potential upstream regulators" = c(
    "wt1b", "gata6", "LOC119894306", "LOC119914475"
  ),
  
  "RA-associated signaling" = c(
    "aldh1a2", "gprc5c", "LOC119884110", "crabp2a"
  )
)

program_dotplots$potential_regulatory <- make_program_dotplots(
  program_name = "Potential regulatory program",
  marker_list = marker_regulatory,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "viridis",
  viridis_option = "rocket",
  subset_color_limits = c(-1.2, 1.0)
)

print(program_dotplots$potential_regulatory$all_domains)
print(program_dotplots$potential_regulatory$macrophage_domains)


# ==============================================================================
# --- 8. Inflammatory and antigen-presentation program ---
# ==============================================================================

marker_inflammatory <- list(
  "Complements" = c(
    "LOC119885585", "c1qb", "LOC119885788",
    "LOC119897430", "LOC119915106", "LOC119896603"
  ),
  
  "MHCII" = c(
    "LOC119888605", "LOC119917015", "LOC119912422",
    "LOC119912423", "LOC119912424", "LOC119912429", "LOC119912432"
  ),
  
  "MHCI" = c(
    "LOC119884279", "LOC119908110", "LOC119907864"
  ),
  
  "Proteases" = c(
    "ctsba", "ctsc", "LOC119890600", "LOC119890271",
    "ctsh", "ctsl.1", "LOC119892265", "ctss1",
    "ctss2.1", "LOC119882210", "ctsz", "napsa"
  ),
  
  "Immune effectors" = c(
    "tnfa", "m17", "LOC119894803", "LOC119890263", "il1b"
  )
)

program_dotplots$inflammatory <- make_program_dotplots(
  program_name = "Inflammatory and antigen-presentation program",
  marker_list = marker_inflammatory,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "viridis",
  viridis_option = "plasma",
  subset_color_limits = c(-1.2, 1.0)
)

print(program_dotplots$inflammatory$all_domains)
print(program_dotplots$inflammatory$macrophage_domains)


# ==============================================================================
# --- 9. Immune regulation and tissue homeostasis program ---
# ==============================================================================

marker_immune_homeostasis <- list(
  "Protease Inhibition" = c(
    "LOC119910060", "LOC119910049", "cst3", "LOC119882640", "cast"
  ),
  
  "Immune Regulation" = c(
    "LOC119884194", "LOC119884197", "nfkbiaa", "il10", "tgfb1a"
  ),
  
  "Stress Adaptation, Survival & Genome Stability" = c(
    "bcl2l1", "si-dkey-243k1.3", "babam2", "LOC119910277",
    "ywhag1", "LOC119891659", "rcan1b", "pkig", "tsc22d1",
    "tsc22d2", "LOC119915309", "LOC119893531", "LOC119893593"
  ),
  
  "Transcriptional regulation" = c(
    "bhlhe40", "hic1", "LOC119899642", "junbb", "LOC119918304"
  )
)

program_dotplots$immune_homeostasis <- make_program_dotplots(
  program_name = "Immune regulation and tissue homeostasis program",
  marker_list = marker_immune_homeostasis,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "viridis",
  viridis_option = "mako",
  subset_color_limits = c(-1.2, 1.0)
)

print(program_dotplots$immune_homeostasis$all_domains)
print(program_dotplots$immune_homeostasis$macrophage_domains)


# ==============================================================================
# --- 10. Oxidative phosphorylation program ---
# ==============================================================================

color_YlGnBu <- colorRampPalette(
  brewer.pal(n = 9, name = "YlGnBu")
)(100)

marker_oxphos <- list(
  "Cytochrome c oxidase" = c(
    "COX1", "COX2", "COX3", "LOC119905811", "LOC119890004",
    "LOC119917832", "LOC119892218", "LOC119911148", "LOC119885605",
    "LOC119882732", "LOC119916265", "LOC119896019",
    "LOC119892403", "LOC119893283"
  ),
  
  "F-type Atpase" = c(
    "ATP6", "LOC119891187", "atp5f1b", "atp5f1c", "atp5f1d",
    "atp5f1e", "atp5po", "atp5pb", "LOC119890133",
    "atp5mc3a", "atp5mc1", "LOC119899395", "LOC119914361",
    "atp5mf", "LOC119881880"
  ),
  
  "NADH dehydrogenase" = c(
    "ND1", "ND2", "ND3", "ND4", "ND5", "ND6",
    "ndufv1", "ndufv2", "ndufs2", "ndufs3",
    "ndufs7", "ndufs8a", "ndufa9a"
  ),
  
  "Cytochrome c reductase" = c(
    "LOC119900817", "LOC119889032", "CYTB"
  )
)

program_dotplots$oxphos <- make_program_dotplots(
  program_name = "Oxidative phosphorylation program",
  marker_list = marker_oxphos,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "gradient",
  gradient_colors = color_YlGnBu,
  subset_color_limits = c(-1.2, 1.3)
)

print(program_dotplots$oxphos$all_domains)
print(program_dotplots$oxphos$macrophage_domains)


# ==============================================================================
# --- 11. Glycolysis program ---
# ==============================================================================

marker_glycolysis <- list(
  "Glycolysis" = c(
    "LOC119918448", "LOC119888631", "ldha", "LOC119895022",
    "LOC119884553", "aldocb", "acss2", "eno1a", "ldhba",
    "pgk1", "gpia", "tpi1b", "aldh16a1", "LOC119896906",
    "LOC119891493", "pgam1b", "aldh7a1", "LOC119912637",
    "pdha1a", "pkma", "LOC119901704", "pdhb",
    "LOC119888263", "dldh"
  )
)

program_dotplots$glycolysis <- make_program_dotplots(
  program_name = "Glycolysis program",
  marker_list = marker_glycolysis,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "gradient",
  gradient_colors = color_YlGnBu,
  subset_color_limits = c(-1.2, 1.3)
)

print(program_dotplots$glycolysis$all_domains)
print(program_dotplots$glycolysis$macrophage_domains)


# ==============================================================================
# --- 12. Metabolic and microenvironment adaptation program ---
# ==============================================================================

color_PuOr <- colorRampPalette(
  brewer.pal(n = 9, name = "PuOr")
)(100)

marker_metabolic_adaptation <- list(
  "Glycogen metabolism" = c(
    "LOC119910845"
  ),
  
  "Amino acid metabolism" = c(
    "LOC119892499", "aass", "LOC119918948", "LOC119890054"
  ),
  
  "Lipid metabolism" = c(
    "LOC119903459", "LOC119898927", "fabp4a",
    "LOC119897230", "LOC119918650", "LOC119918651", "plin2"
  ),
  
  "Nucleotide metabolism" = c(
    "cdab"
  ),
  
  "Inositol pyrophosphate metabolism" = c(
    "nudt4b"
  ),
  
  "Phosphocreatine transport" = c(
    "LOC119893713", "LOC119910978"
  ),
  
  "Acid-Base and CO2 Homeostasis" = c(
    "LOC119912177"
  ),
  
  "Microenvironment Adaptation" = c(
    "ndrg1a", "nupr1b", "egln3", "LOC119900507",
    "flt1", "ace", "si-ch211-202p1.5", "vegfab"
  )
)

program_dotplots$metabolic_adaptation <- make_program_dotplots(
  program_name = "Metabolic and microenvironment adaptation program",
  marker_list = marker_metabolic_adaptation,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "gradient",
  gradient_colors = color_PuOr,
  subset_color_limits = c(-1.2, 1.0)
)

print(program_dotplots$metabolic_adaptation$all_domains)
print(program_dotplots$metabolic_adaptation$macrophage_domains)


# ==============================================================================
# --- 13. Transporter and channel program ---
# ==============================================================================

color_RdYlBu <- colorRampPalette(
  rev(brewer.pal(n = 11, name = "RdYlBu"))
)(100)

marker_transporters <- list(
  "Water and inorganic ions" = c(
    "LOC119901983", "rhbg", "LOC119904410", "atp1b1a",
    "LOC119912124", "kcnk5a", "slc12a7b", "LOC119908031",
    "slc9a3r1b", "chp1", "LOC119918691", "slc39a8"
  ),
  
  "Amino acids, peptides and neurotransmitters" = c(
    "slc6a14", "LOC119918306", "slc1a5", "slc1a3a",
    "slc15a2", "LOC119885976", "slc6a8", "LOC119905556"
  ),
  
  "Organic acids" = c(
    "slc5a8l", "LOC119882223"
  ),
  
  "Vitamins" = c(
    "slc23a2"
  ),
  
  "Nucleosides" = c(
    "slc28a1"
  ),
  
  "ADP/ATP" = c(
    "si-dkey-251i10.1"
  ),
  
  "Unknown" = c(
    "slc10a3", "slc25a55a"
  )
)

program_dotplots$transporters_channels <- make_program_dotplots(
  program_name = "Transporter and channel program",
  marker_list = marker_transporters,
  object_all = seu_int_rpca,
  object_subset = object_sub,
  palette_type = "gradient",
  gradient_colors = color_RdYlBu,
  subset_color_limits = c(-1.2, 1.0)
)

print(program_dotplots$transporters_channels$all_domains)
print(program_dotplots$transporters_channels$macrophage_domains)


# ==============================================================================
# --- 14. Fibroblast-macrophage crosstalk and ECM support program ---
# ==============================================================================

color_Blue <- colorRampPalette(
  brewer.pal(n = 11, name = "RdYlBu")
)(100)

marker_fibro_mac <- list(
  "Structural ECM Proteins" = c(
    "col1a1a", "col1a1b", "col1a2", "LOC119904231",
    "col5a1", "col5a2a", "col6a1", "col6a2",
    "LOC119904002", "LOC119903447", "fn1b"
  ),
  
  "ECM Modulators & Remodeling Enzymes" = c(
    "mmp2", "sparc", "LOC119882173", "dcn",
    "LOC119882174", "pcolcea"
  ),
  
  "Cellular Signaling Factors" = c(
    "ccn1", "LOC119909085", "fstl1b", "ntd5", "id3", "rbp4"
  ),
  
  "E-Mac-related Paracrine & Remodeling Factors" = c(
    "LOC119888537", "bmp1a", "p4ha1b", "loxa",
    "LOC119897617", "LOC119886711"
  )
)

program_dotplots$fibroblast_macrophage_crosstalk <- make_program_dotplots(
  program_name = "Fibroblast-macrophage crosstalk program",
  marker_list = marker_fibro_mac,
  object_all = seu_int_rpca,
  object_subset = NULL,
  palette_type = "gradient",
  gradient_colors = color_Blue,
  all_color_limits = c(-2.3, 2.3)
)

print(program_dotplots$fibroblast_macrophage_crosstalk$all_domains)


# ==============================================================================
# --- 15. Session information ---
# ==============================================================================

sessionInfo()