# ==============================================================================
# Head Kidney Granuloma - 5. Module Scoring and Raincloud Visualization
# ==============================================================================
#
# Purpose:
#   Calculate module scores for functional gene programs in the integrated
#   head kidney spatial transcriptomics dataset and visualize these scores
#   across annotated spatial domains.
#
# Required input:
#   seu_int_rpca:
#     Integrated and annotated Seurat object generated by:
#       01_HK_ST_Control_Infected_RPCA_Integration.R
#       02_HK_ST_Integrated_Domain_Annotation.R
#
# Main outputs generated in memory:
#   module_score_mapping
#   module_score_plots
#
# Notes:
#   This script does not save figures to disk. Users can export plots as needed.
# ==============================================================================


# ==============================================================================
# --- 0. Load R packages ---
# ==============================================================================

suppressMessages({
  library(Seurat)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(RColorBrewer)
  library(scales)
  library(ggpubr)
  library(gghalves)
})

options(future.globals.maxSize = 9e10)
options(Seurat.object.assay.version = "v5")


# ==============================================================================
# --- 1. Example input object loading ---
# ==============================================================================

project_dir <- "path/to/project"

annotated_object_path <- file.path(
  project_dir,
  "processed_objects",
  "head_kidney_control_infected_RPCA_integrated_annotated.rds"
)

if (!exists("seu_int_rpca")) {
  seu_int_rpca <- readRDS(annotated_object_path)
}

DefaultAssay(seu_int_rpca) <- "SCT"

message("Input object:")
print(seu_int_rpca)

message("Current identity classes:")
print(table(Idents(seu_int_rpca), seu_int_rpca$orig.ident))


# ==============================================================================
# --- 2. Color palettes and cluster colors ---
# ==============================================================================

# White-to-purple palette used for spatial module score visualization.
color_wp <- colorRampPalette(c("white", "purple"))(100)

# Define cluster colors if not provided by upstream scripts.
if (!exists("cluster_colors")) {
  cluster_colors <- c(
    "Eryt"                              = "pink",
    "Eryt (Intravascular)"              = "#CC79A7",
    "Gran-Eryt (Homeostatic)"           = "#FFFFCC",
    "Gran (Homeostatic)"                = "#FFDBB7",
    "Gran (Infection-associated)"       = "#FFBA75",
    "Mac (Homeostatic)"                 = "#4169E1",
    "Mac (Infection-associated)"        = "#000080",
    "Outer E-Mac"                       = "grey",
    "Inner E-Mac"                       = "#CAFCFE",
    "B (Homeostatic)"                   = "#A6CEE3",
    "Lymphocyte"                        = "red",
    "Vascular niche (Fibro-mixed)"      = "#8B4513"
  )
}


# ==============================================================================
# --- 3. Define functional gene modules ---
# ==============================================================================

functional_modules <- list(
  
  "Cell Junctions" = c(
    "LOC119917376", "jupa", "ctnna1", "ctnnd1",
    "dsc2l", "LOC119902058", "LOC119905441", "LOC119889888",
    "dspa", "LOC119917243",
    "cldn5a", "LOC119900663", "cldn11a", "tjp1a", "cgnl1",
    "LOC119908847", "LOC119908668"
  ),
  
  "Cytoskeletal architecture and regulatory program" = c(
    "LOC119905733", "LOC119886877", "krt15", "LOC119886876",
    "krt94", "krt99", "eppk1", "LOC119912524",
    "LOC119886962", "tgm1l1",
    "LOC119885789", "LOC119909726", "LOC119895369",
    "pof1b", "LOC119901854", "crip1", "crip2", "nudcd2",
    "ahnak", "LOC119909740", "ezrb", "ehd2b", "stoml3b",
    "LOC119914141", "mpp6b", "anxa1a", "LOC119888099",
    "anxa2a", "LOC119890527", "LOC119898827", "anxa11a",
    "anxa13",
    "s100a10a", "si-ch211-105c13.3", "s100v2", "calm1b",
    "capns1b", "LOC119912040", "LOC119915637", "LOC119886455",
    "efnb2a", "plekhg5b", "limk2", "cdc42ep3",
    "ppp2cab", "ppp1r27b", "rnd3a", "plekhn1", "LOC119890724"
  ),
  
  "Extracellular matrix remodeling program" = c(
    "mmp2", "mmp15b", "mmp19", "adam8a", "adam11", "LOC119886402",
    "serpine1", "serpine2", "LOC119908472", "LOC119906979",
    "timp2a", "timp2b", "LOC119918277",
    "ero1a", "p4hb", "cd44b", "tnfaip6", "fn1a", "fn1b",
    "LOC119897849", "cav1", "cavin1b", "LOC119907497",
    "LOC119918071", "cd81a", "LOC119893200", "LOC119895007",
    "LOC119899685", "vwa11", "anos1b", "aplp2", "prom2",
    "LOC119886359",
    "itga3b", "itga5", "LOC119902203", "itgav",
    "LOC119901714", "LOC119892793", "LOC119915730", "itgb6"
  ),
  
  "Potential regulatory program" = c(
    "spaca4l", "LOC119906807", "zanl",
    "wt1b", "gata6", "LOC119894306", "LOC119914475",
    "aldh1a2", "gprc5c", "LOC119884110", "crabp2a"
  ),
  
  "Inflammatory program" = c(
    "LOC119885585", "c1qb", "LOC119885788", "LOC119897430",
    "LOC119892056", "LOC119915106", "LOC119896603",
    "LOC119888605", "LOC119917015", "LOC119912422",
    "LOC119912423", "LOC119912424", "LOC119912429",
    "LOC119912432",
    "LOC119884279", "LOC119908110", "LOC119907864",
    "ctsba", "ctsc", "LOC119890600", "LOC119890271",
    "ctsh", "ctsl.1", "LOC119892265", "ctss1",
    "ctss2.1", "LOC119882210", "ctsz", "napsa",
    "tnfa", "m17", "LOC119894803", "LOC119890263", "il1b"
  ),
  
  "Immune regulation and tissue homeostasis program" = c(
    "LOC119910060", "LOC119910049", "cst3", "LOC119882640", "cast",
    "LOC119884194", "LOC119884197", "nfkbiaa", "il10", "tgfb1a",
    "bcl2l1", "si-dkey-243k1.3", "babam2", "LOC119910277",
    "ywhag1", "LOC119891659", "rcan1b", "pkig",
    "tsc22d1", "tsc22d2", "LOC119915309",
    "LOC119893531", "LOC119893593",
    "bhlhe40", "hic1", "LOC119899642", "junbb", "LOC119918304"
  ),
  
  "Oxidative phosphorylation program" = c(
    "COX1", "COX2", "COX3", "LOC119905811", "LOC119890004",
    "LOC119917832", "LOC119892218", "LOC119893803",
    "LOC119897473", "LOC119907810", "LOC119911148",
    "LOC119885605", "LOC119881863", "LOC119882732",
    "LOC119909213", "LOC119916265", "LOC119896019",
    "LOC119892403", "LOC119887585", "LOC119893283",
    "LOC119910933",
    "ATP6", "LOC119891187", "atp5fa1", "atp5f1b",
    "atp5f1c", "atp5f1d", "atp5f1e", "atp5po",
    "atp5pb", "LOC119915245", "LOC119890133",
    "LOC119903517", "atp5mc3a", "atp5mc1", "atp5pd",
    "LOC119899395", "LOC119914361", "atp5mf",
    "LOC119881880", "atp5l", "LOC119901952",
    "atp5pf", "atp5mj", "atp5md",
    "ND1", "ND2", "ND3", "ND4", "ND5", "ND6",
    "ndufv1", "ndufv2", "ndufs2", "ndufs3",
    "ndufs7", "ndufs8a", "ndufa9a", "ndufab1b",
    "LOC119900817", "LOC119889032", "CYTB"
  ),
  
  "Metabolic adaptation program" = c(
    "LOC119892499", "aass", "LOC119918948",
    "LOC119903459", "LOC119898927", "fabp4a",
    "LOC119897230", "LOC119918650", "LOC119918651", "plin2",
    "cdab", "nudt4b", "LOC119893713", "LOC119910978",
    "LOC119912177",
    "ndrg1a", "nupr1b", "egln3", "LOC119900507",
    "flt1", "ace"
  ),
  
  "Transporter and channel program" = c(
    "LOC119901983", "rhbg", "LOC119904410", "atp1b1a",
    "LOC119912124", "kcnk5a", "slc12a7b", "LOC119908031",
    "slc9a3r1b", "chp1", "LOC119918691", "slc39a8",
    "slc6a14", "LOC119918306", "slc1a5", "slc1a3a",
    "slc15a2", "LOC119885976", "slc6a8", "LOC119905556",
    "slc5a8l", "LOC119882223", "slc23a2", "slc28a1",
    "slc10a3", "slc25a55a"
  ),
  
  "Fibroblast-macrophage crosstalk program" = c(
    "col1a1a", "col1a1b", "col1a2", "LOC119904231",
    "col5a1", "col5a2a", "col6a1", "col6a2",
    "LOC119904002", "LOC119903447", "fn1b",
    "mmp2", "sparc", "LOC119882173", "dcn",
    "LOC119882174", "pcolcea",
    "ccn1", "LOC119909085", "fstl1b", "ntd5", "id3", "rbp4",
    "loxa", "bmp1a", "LOC119897617", "LOC119886711",
    "LOC119888537"
  )
)


# ==============================================================================
# --- 4. Filter module gene lists according to object features ---
# ==============================================================================

filter_module_genes <- function(gene_list, object) {
  
  filtered <- lapply(gene_list, function(x) {
    x[x %in% rownames(object)]
  })
  
  missing_genes <- lapply(names(gene_list), function(module_name) {
    setdiff(gene_list[[module_name]], filtered[[module_name]])
  })
  names(missing_genes) <- names(gene_list)
  
  for (module_name in names(missing_genes)) {
    if (length(missing_genes[[module_name]]) > 0) {
      warning(
        "Missing genes in module '", module_name, "': ",
        paste(missing_genes[[module_name]], collapse = ", ")
      )
    }
  }
  
  filtered <- filtered[lengths(filtered) > 0]
  return(filtered)
}

functional_modules_filtered <- filter_module_genes(
  gene_list = functional_modules,
  object = seu_int_rpca
)


# ==============================================================================
# --- 5. Calculate module scores ---
# ==============================================================================

set.seed(1)

score_prefix <- "HKST_ModuleScore_"

seu_int_rpca <- AddModuleScore(
  object = seu_int_rpca,
  features = functional_modules_filtered,
  name = score_prefix,
  assay = "SCT",
  seed = 1
)

module_score_mapping <- tibble(
  module = names(functional_modules_filtered),
  score_column = paste0(score_prefix, seq_along(functional_modules_filtered))
)

print(module_score_mapping)


# ==============================================================================
# --- 6. Prepare macrophage-related subset ---
# ==============================================================================

macrophage_groups <- c(
  "Mac (Homeostatic)",
  "Mac (Infection-associated)",
  "Outer E-Mac",
  "Inner E-Mac"
)

macrophage_groups_present <- intersect(
  macrophage_groups,
  levels(Idents(seu_int_rpca))
)

missing_macrophage_groups <- setdiff(
  macrophage_groups,
  macrophage_groups_present
)

if (length(missing_macrophage_groups) > 0) {
  warning(
    "The following macrophage-related groups are missing: ",
    paste(missing_macrophage_groups, collapse = ", ")
  )
}

object_sub <- subset(
  x = seu_int_rpca,
  cells = WhichCells(seu_int_rpca, idents = macrophage_groups_present)
)

message("Macrophage-related subset:")
print(table(Idents(object_sub), object_sub$orig.ident))


# ==============================================================================
# --- 7. Helper functions for module score visualization ---
# ==============================================================================

make_score_dataframe <- function(object, score_column) {
  
  score_df <- FetchData(
    object = object,
    vars = score_column
  ) %>%
    tibble::rownames_to_column("cell_id") %>%
    mutate(
      ident = as.character(Idents(object)[cell_id]),
      score = .data[[score_column]]
    )
  
  score_df$ident <- factor(
    score_df$ident,
    levels = levels(Idents(object))
  )
  
  return(score_df)
}


get_valid_comparisons <- function(comparisons, available_groups) {
  
  valid <- lapply(comparisons, function(x) {
    if (all(x %in% available_groups)) {
      return(x)
    } else {
      return(NULL)
    }
  })
  
  valid <- valid[!sapply(valid, is.null)]
  return(valid)
}


make_spatial_score_plot <- function(object, score_column, module_name) {
  
  p <- SpatialFeaturePlot(
    object = object,
    features = score_column,
    image.alpha = 0,
    pt.size.factor = 4,
    ncol = 2,
    crop = FALSE
  ) &
    scale_fill_gradientn(
      colors = color_wp,
      limits = c(0, NA),
      oob = scales::squish
    ) &
    ggtitle(module_name)
  
  return(p)
}


make_violin_score_plot <- function(object, score_column, module_name) {
  
  plot_data <- make_score_dataframe(
    object = object,
    score_column = score_column
  )
  
  comparisons <- list(
    c("Outer E-Mac", "Mac (Homeostatic)"),
    c("Inner E-Mac", "Mac (Infection-associated)")
  )
  
  comparisons <- get_valid_comparisons(
    comparisons = comparisons,
    available_groups = unique(as.character(plot_data$ident))
  )
  
  p <- ggplot(
    plot_data,
    aes(x = ident, y = score, fill = ident)
  ) +
    geom_violin(
      trim = FALSE,
      scale = "width",
      alpha = 0.8
    ) +
    geom_jitter(
      shape = 16,
      position = position_jitter(width = 0.15),
      size = 0.5,
      alpha = 0.4
    ) +
    scale_fill_manual(values = cluster_colors) +
    theme_classic(base_size = 14) +
    theme(
      axis.text.x = element_text(
        angle = 45,
        hjust = 1,
        size = 12,
        face = "bold"
      ),
      axis.text.y = element_text(size = 12),
      axis.title = element_text(size = 14, face = "bold"),
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      legend.position = "none"
    ) +
    labs(
      title = paste0(module_name, " Signature Score"),
      x = "Spatial domain",
      y = "Signature score"
    )
  
  if (length(comparisons) > 0) {
    y_max <- max(plot_data$score, na.rm = TRUE)
    label_y <- seq(
      from = y_max * 1.05,
      by = y_max * 0.10,
      length.out = length(comparisons)
    )
    
    p <- p +
      stat_compare_means(
        comparisons = comparisons,
        method = "wilcox.test",
        label = "p.signif",
        label.y = label_y,
        size = 5
      ) +
      coord_cartesian(
        ylim = c(NA, max(label_y, na.rm = TRUE) * 1.10)
      )
  }
  
  return(p)
}


make_raincloud_score_plot <- function(object, score_column, module_name) {
  
  plot_data <- make_score_dataframe(
    object = object,
    score_column = score_column
  )
  
  comparisons <- list(
    c("Outer E-Mac", "Mac (Homeostatic)"),
    c("Inner E-Mac", "Mac (Infection-associated)")
  )
  
  comparisons <- get_valid_comparisons(
    comparisons = comparisons,
    available_groups = unique(as.character(plot_data$ident))
  )
  
  p <- ggplot(
    plot_data,
    aes(x = ident, y = score, fill = ident)
  ) +
    geom_half_violin(
      side = "r",
      trim = FALSE,
      scale = "width",
      alpha = 0.7
    ) +
    geom_half_boxplot(
      side = "r",
      width = 0.2,
      outlier.shape = 16,
      outlier.size = 0,
      alpha = 0.3
    ) +
    geom_half_point(
      side = "l",
      width = 0.2,
      size = 0.6,
      alpha = 0.3
    ) +
    scale_fill_manual(values = cluster_colors) +
    theme_classic(base_size = 14) +
    theme(
      axis.text.x = element_text(size = 12, face = "bold"),
      axis.text.y = element_text(size = 12),
      axis.title = element_text(size = 14, face = "bold"),
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      legend.position = "none"
    ) +
    labs(
      title = paste0(module_name, " Score"),
      x = "Spatial domain",
      y = "Score"
    )
  
  if (length(comparisons) > 0) {
    y_max <- max(plot_data$score, na.rm = TRUE)
    label_y <- seq(
      from = y_max * 1.05,
      by = y_max * 0.12,
      length.out = length(comparisons)
    )
    
    p <- p +
      stat_compare_means(
        comparisons = comparisons,
        method = "wilcox.test",
        label = "p.signif",
        label.y = label_y,
        size = 6
      ) +
      coord_cartesian(
        ylim = c(NA, max(label_y, na.rm = TRUE) * 1.15),
        clip = "off"
      )
  }
  
  return(p)
}


# ==============================================================================
# --- 8. Generate module score plots ---
# ==============================================================================

module_score_plots <- list()

for (i in seq_len(nrow(module_score_mapping))) {
  
  module_name <- module_score_mapping$module[i]
  score_column <- module_score_mapping$score_column[i]
  
  message("Generating plots for module: ", module_name)
  
  module_score_plots[[module_name]] <- list(
    spatial_score = make_spatial_score_plot(
      object = seu_int_rpca,
      score_column = score_column,
      module_name = module_name
    ),
    
    violin_all_domains = make_violin_score_plot(
      object = seu_int_rpca,
      score_column = score_column,
      module_name = module_name
    ),
    
    raincloud_macrophage_domains = make_raincloud_score_plot(
      object = object_sub,
      score_column = score_column,
      module_name = module_name
    )
  )
}


# Example: print one module.
print(module_score_plots[["Cell Junctions"]]$spatial_score)
print(module_score_plots[["Cell Junctions"]]$raincloud_macrophage_domains)


# ==============================================================================
# --- 9. Session information ---
# ==============================================================================

sessionInfo()