# ==============================================================================
# Head Kidney Granuloma - 6. Spatial Feature Mapping of Representative Genes
# ==============================================================================
#
# Purpose:
#   Generate spatial feature plots for representative genes from functional
#   programs in the integrated and annotated head kidney spatial transcriptomics
#   dataset.
#
# Required input:
#   seu_int_rpca:
#     Integrated and annotated Seurat object generated by:
#       01_HK_ST_Control_Infected_RPCA_Integration.R
#       02_HK_ST_Integrated_Domain_Annotation.R
#
# Main outputs generated in memory:
#   spatial_feature_plots
#
# Notes:
#   This script does not save figures to disk. Users can export plots as needed.
# ==============================================================================


# ==============================================================================
# --- 0. Load R packages ---
# ==============================================================================

suppressMessages({
  library(Seurat)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(RColorBrewer)
  library(scales)
  library(viridis)
  library(scico)
})

options(future.globals.maxSize = 9e10)
options(Seurat.object.assay.version = "v5")


# ==============================================================================
# --- 1. Example input object loading ---
# ==============================================================================

project_dir <- "path/to/project"

annotated_object_path <- file.path(
  project_dir,
  "processed_objects",
  "head_kidney_control_infected_RPCA_integrated_annotated.rds"
)

if (!exists("seu_int_rpca")) {
  seu_int_rpca <- readRDS(annotated_object_path)
}

DefaultAssay(seu_int_rpca) <- "SCT"

message("Input object:")
print(seu_int_rpca)

message("Current identity classes:")
print(table(Idents(seu_int_rpca), seu_int_rpca$orig.ident))


# ==============================================================================
# --- 2. Define representative gene programs for spatial mapping ---
# ==============================================================================

spatial_gene_programs <- list(
  
  "Cell Junctions" = list(
    "Adherens Junction" = c(
      "LOC119917376", "cdh11", "jupa", "ctnna1", "ctnnb1", "ctnnd1"
    ),
    "Desmosome" = c(
      "dsc2l", "LOC119902058", "LOC119905441", "LOC119889888",
      "pkp3a", "pkp4", "dspa", "LOC119917243"
    ),
    "Tight Junction" = c(
      "cldn5a", "LOC119900663", "cldn11a", "tjp1a", "cgnl1"
    ),
    "Gap Junction" = c(
      "LOC119908847", "LOC119908668"
    )
  ),
  
  "Cytoskeletal architecture and regulatory program" = list(
    "Keratin Cytoskeleton" = c(
      "LOC119905733", "LOC119886877", "krt15", "LOC119886876",
      "krt94", "krt99", "eppk1", "LOC119912524",
      "LOC119886962", "tgm1l1"
    ),
    "Actin Cytoskeleton and Organization" = c(
      "LOC119885789", "LOC119909726", "LOC119895369",
      "pof1b", "LOC119901854", "crip1", "crip2", "nudcd2"
    ),
    "Membrane-Cytoskeleton Coupling and Repair" = c(
      "ahnak", "LOC119909740", "ezrb", "ehd2b", "stoml3b",
      "LOC119914141", "mpp6b", "anxa1a", "LOC119888099",
      "anxa2a", "LOC119890527", "LOC119898827",
      "anxa11a", "anxa13"
    ),
    "Calcium Signaling" = c(
      "s100a10a", "si-ch211-105c13.3", "s100v2", "calm1b",
      "capns1b", "LOC119912040", "LOC119915637", "LOC119886455"
    ),
    "Rho GTPase Signaling" = c(
      "efnb2a", "plekhg5b", "limk2", "cdc42ep3",
      "ppp2cab", "ppp1r27b", "rnd3a", "plekhn1", "LOC119890724"
    )
  ),
  
  "Extracellular matrix remodeling program" = list(
    "ECM Proteases" = c(
      "mmp2", "mmp15b", "mmp19", "adam8a", "adam11", "LOC119886402"
    ),
    "ECM Proteolysis Inhibitors" = c(
      "serpine1", "serpine2", "LOC119908472", "LOC119906979",
      "timp2a", "timp2b", "LOC119918277"
    ),
    "Cell-Matrix Adhesion and Transmembrane Anchorage" = c(
      "ero1a", "p4hb", "cd44b", "tnfaip6", "fn1a", "fn1b",
      "LOC119897849", "cav1", "cavin1b", "LOC119907497",
      "LOC119918071", "cd81a", "LOC119893200", "LOC119895007",
      "LOC119899685", "vwa11", "anos1b", "aplp2", "prom2",
      "LOC119886359"
    ),
    "Integrins" = c(
      "itga3b", "itga5", "LOC119902203", "itgav",
      "LOC119901714", "LOC119892793", "LOC119915730", "itgb6"
    )
  ),
  
  "Potential regulatory program" = list(
    "Potential membrane microdomain organizers" = c(
      "spaca4l", "LOC119906807", "zanl"
    ),
    "Potential upstream regulators" = c(
      "wt1b", "gata6", "LOC119894306", "LOC119914475"
    ),
    "RA-associated signaling" = c(
      "aldh1a2", "gprc5c", "LOC119884110", "crabp2a"
    )
  ),
  
  "Inflammatory and antigen-presentation program" = list(
    "Complements" = c(
      "LOC119885585", "c1qb", "LOC119885788", "LOC119897430",
      "LOC119892056", "LOC119915106", "LOC119896603"
    ),
    "MHCII" = c(
      "LOC119888605", "LOC119917015", "LOC119912422",
      "LOC119912429", "LOC119912010"
    ),
    "MHCI" = c(
      "LOC119884279", "LOC119908110", "LOC119907864"
    ),
    "Proteases" = c(
      "ctsba", "ctsc", "LOC119890600", "LOC119890271",
      "ctsh", "ctsk", "LOC119882211", "ctsl.1",
      "LOC119892265", "ctss1", "ctss2.1",
      "LOC119882210", "ctsz", "napsa"
    ),
    "Immune effectors" = c(
      "tnfa", "m17", "LOC119894803", "LOC119890263", "il1b"
    )
  ),
  
  "Immune regulation and tissue homeostasis program" = list(
    "Protease Inhibition" = c(
      "LOC119910060", "LOC119910049", "cst3", "LOC119882640", "cast"
    ),
    "Immune Regulation" = c(
      "LOC119884194", "LOC119884197", "nfkbiaa", "il10", "tgfb1a", "aicda"
    ),
    "Stress Adaptation" = c(
      "mcl1b", "bcl2l1", "si-dkey-243k1.3", "babam2",
      "LOC119910277", "ywhag1", "LOC119891659",
      "rcan1b", "pkig", "tsc22d1", "tsc22d2",
      "LOC119915309", "LOC119893531", "LOC119893593"
    ),
    "Transcriptional regulation" = c(
      "bhlhe40", "hic1", "LOC119899642", "junbb", "LOC119918304"
    )
  ),
  
  "Oxidative phosphorylation program" = list(
    "Cytochrome c oxidase" = c(
      "COX1", "COX2", "COX3", "LOC119905811", "LOC119890004",
      "LOC119917832", "LOC119892218", "LOC119911148",
      "LOC119885605", "LOC119882732", "LOC119916265",
      "LOC119896019", "LOC119892403", "LOC119893283"
    ),
    "F-type ATPase" = c(
      "ATP6", "LOC119891187", "atp5f1b", "atp5f1c",
      "atp5f1d", "atp5f1e", "atp5po", "atp5pb",
      "LOC119890133", "atp5mc3a", "atp5mc1",
      "LOC119899395", "LOC119914361", "atp5mf",
      "LOC119881880", "atp5pf", "atp5mj", "atp5md"
    ),
    "NADH dehydrogenase" = c(
      "ND1", "ND2", "ND3", "ND4", "ND5", "ND6",
      "ndufv1", "ndufv2", "ndufs2", "ndufs3",
      "ndufs7", "ndufs8a", "ndufa9a"
    ),
    "Cytochrome c reductase" = c(
      "LOC119900817", "LOC119889032", "CYTB"
    )
  ),
  
  "Glycolysis program" = list(
    "Glycolysis" = c(
      "LOC119918448", "LOC119888631", "ldha", "LOC119895022",
      "LOC119884553", "aldocb", "acss2", "eno1a", "ldhba",
      "pgk1", "gpia", "tpi1b", "aldh16a1", "LOC119896906",
      "LOC119891493", "pgam1b", "aldh7a1", "LOC119912637",
      "pdha1a", "pkma", "LOC119901704", "pdhb",
      "LOC119888263", "dldh"
    )
  ),
  
  "Metabolic and microenvironment adaptation program" = list(
    "Amino acid metabolism" = c(
      "LOC119892499", "aass", "LOC119918948"
    ),
    "Lipid metabolism" = c(
      "LOC119903459", "LOC119898927", "fabp4a",
      "LOC119897230", "LOC119918650", "LOC119918651", "plin2"
    ),
    "Nucleotide metabolism" = c(
      "cdab"
    ),
    "Inositol pyrophosphate metabolism" = c(
      "nudt4b"
    ),
    "Phosphocreatine transport" = c(
      "LOC119893713", "LOC119910978"
    ),
    "Acid-Base and CO2 Homeostasis" = c(
      "LOC119912177"
    ),
    "Microenvironment Adaptation" = c(
      "ndrg1a", "nupr1b", "egln3", "LOC119900507", "flt1", "ace"
    )
  ),
  
  "Transporter and channel program" = list(
    "Water and inorganic ions" = c(
      "LOC119901983", "rhbg", "LOC119904410", "atp1b1a",
      "LOC119912124", "kcnk5a", "slc12a7b",
      "LOC119908031", "slc9a3r1b", "chp1",
      "LOC119918691", "slc39a8"
    ),
    "Amino acids, peptides and neurotransmitters" = c(
      "slc6a14", "LOC119918306", "slc1a5", "slc1a3a",
      "slc15a2", "LOC119885976", "slc6a8", "LOC119905556"
    ),
    "Organic Acids" = c(
      "slc5a8l", "LOC119882223"
    ),
    "Vitamins" = c(
      "slc23a2"
    ),
    "Nucleosides" = c(
      "slc28a1"
    ),
    "ADP/ATP" = c(
      "si-dkey-251i10.1"
    ),
    "Mitochondrial energy and metabolism" = c(
      "slc10a3", "slc25a55a"
    )
  ),
  
  "Fibroblast-macrophage crosstalk program" = list(
    "Structural ECM Proteins" = c(
      "col1a1a", "col1a1b", "col1a2", "LOC119904231",
      "col5a1", "col5a2a", "col6a1", "col6a2",
      "LOC119904002", "LOC119903447", "fn1b"
    ),
    "ECM Modulators and Remodeling Enzymes" = c(
      "mmp2", "sparc", "LOC119882173", "dcn",
      "LOC119882174", "pcolcea"
    ),
    "Cellular Signaling Factors" = c(
      "ccn1", "LOC119909085", "fstl1b", "ntd5", "id3", "rbp4"
    ),
    "E-Mac-related Paracrine and Remodeling Factors" = c(
      "loxa", "bmp1a", "LOC119897617", "LOC119886711", "LOC119888537"
    )
  ),
  
  "Chemokines" = list(
    "Chemokines" = c(
      "LOC119891695", "LOC119896802", "LOC119888586",
      "LOC119888585", "LOC119888587", "LOC119896801"
    )
  )
)


# ==============================================================================
# --- 3. Flatten nested gene program list ---
# ==============================================================================

flatten_gene_programs <- function(program_list) {
  
  flattened <- list()
  
  for (program_name in names(program_list)) {
    for (submodule_name in names(program_list[[program_name]])) {
      
      new_name <- paste(program_name, submodule_name, sep = " - ")
      flattened[[new_name]] <- program_list[[program_name]][[submodule_name]]
    }
  }
  
  return(flattened)
}

spatial_gene_sets <- flatten_gene_programs(spatial_gene_programs)


# ==============================================================================
# --- 4. Helper function for spatial feature plotting ---
# ==============================================================================

filter_genes_present <- function(genes, object) {
  
  genes_present <- genes[genes %in% rownames(object)]
  genes_missing <- setdiff(genes, genes_present)
  
  if (length(genes_missing) > 0) {
    warning(
      "The following genes were not found and will be skipped: ",
      paste(genes_missing, collapse = ", ")
    )
  }
  
  return(genes_present)
}


make_spatial_feature_plots <- function(
    object,
    genes,
    program_name,
    slot_use = "data",
    image_alpha = 0,
    point_size_factor = 4,
    crop = FALSE,
    ncol = 2,
    palette = c("scico_oslo", "viridis_magma", "viridis_viridis", "viridis_mako",
                "viridis_rocket", "white_purple", "white_red", "blue"),
    lower_limit = 0,
    upper_limit = NA_real_
) {
  
  palette <- match.arg(palette)
  
  genes_present <- filter_genes_present(
    genes = genes,
    object = object
  )
  
  if (length(genes_present) == 0) {
    warning("No genes available for program: ", program_name)
    return(NULL)
  }
  
  plot_list <- list()
  
  for (gene in genes_present) {
    
    p <- SpatialFeaturePlot(
      object = object,
      features = gene,
      image.alpha = image_alpha,
      pt.size.factor = point_size_factor,
      slot = slot_use,
      crop = crop,
      ncol = ncol
    )
    
    if (palette == "scico_oslo") {
      p <- p &
        scale_fill_scico(
          palette = "oslo",
          direction = -1,
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_magma") {
      p <- p &
        scale_fill_viridis(
          option = "magma",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_viridis") {
      p <- p &
        scale_fill_viridis(
          option = "viridis",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_mako") {
      p <- p &
        scale_fill_viridis(
          option = "mako",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "viridis_rocket") {
      p <- p &
        scale_fill_viridis(
          option = "rocket",
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "white_purple") {
      color_wp <- colorRampPalette(c("white", "purple"))(100)
      
      p <- p &
        scale_fill_gradientn(
          colors = color_wp,
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "white_red") {
      color_wr <- colorRampPalette(c("white", "red"))(100)
      
      p <- p &
        scale_fill_gradientn(
          colors = color_wr,
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    if (palette == "blue") {
      p <- p &
        scale_fill_distiller(
          palette = "Blues",
          direction = 1,
          limits = c(lower_limit, upper_limit),
          oob = scales::squish
        )
    }
    
    p <- p &
      ggtitle(paste0(program_name, " - ", gene))
    
    plot_list[[gene]] <- p
  }
  
  return(plot_list)
}


# ==============================================================================
# --- 5. Select gene programs for spatial mapping ---
# ==============================================================================

# Option 1:
#   Plot only selected programs.
selected_programs <- c(
  "Chemokines - Chemokines"
)

# Option 2:
#   Plot all programs.
# selected_programs <- names(spatial_gene_sets)

selected_programs <- intersect(
  selected_programs,
  names(spatial_gene_sets)
)

if (length(selected_programs) == 0) {
  stop("No selected programs were found in spatial_gene_sets.")
}


# ==============================================================================
# --- 6. Generate spatial feature plots ---
# ==============================================================================

spatial_feature_plots <- list()

for (program_name in selected_programs) {
  
  message("Generating spatial feature plots for: ", program_name)
  
  spatial_feature_plots[[program_name]] <- make_spatial_feature_plots(
    object = seu_int_rpca,
    genes = spatial_gene_sets[[program_name]],
    program_name = program_name,
    slot_use = "data",
    image_alpha = 0,
    point_size_factor = 4,
    crop = FALSE,
    ncol = 2,
    palette = "scico_oslo",
    lower_limit = 0,
    upper_limit = NA_real_
  )
}


# Example:
# Print all chemokine spatial feature plots.
if ("Chemokines - Chemokines" %in% names(spatial_feature_plots)) {
  
  for (gene in names(spatial_feature_plots[["Chemokines - Chemokines"]])) {
    print(spatial_feature_plots[["Chemokines - Chemokines"]][[gene]])
  }
}


# ==============================================================================
# --- 7. Session information ---
# ==============================================================================

sessionInfo()